#!/bin/sh

npm run re:build

npx prettier --write .

npm run re:format

# Check that the code is compiling properly
if [ $? -ne 0 ]; then
    echo "ReScript build failed. Aborting commit."
    exit 1
else 
    echo "✨ Code compiled successfully. ✨"
    exit 0
fi
