// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AuthWrapper from "./AuthWrapper.bs.js";
import * as GlobalProvider from "../Provider/GlobalProvider.bs.js";
import * as HyperSwitchApp from "../HyperSwitchApp.bs.js";
import * as AuthInfoProvider from "../../context/AuthInfoProvider.bs.js";

function AuthEntry(props) {
  return React.createElement(AuthInfoProvider.make, {
    children: React.createElement(AuthWrapper.make, {
      children: React.createElement(GlobalProvider.make, {
        children: React.createElement(HyperSwitchApp.make, {}),
      }),
    }),
  });
}

var make = AuthEntry;

export { make };
/* react Not a pure module */
