// Generated by ReScript, PLEASE EDIT WITH CARE

var Language = {};

var $$Range = {};

var IStandaloneCodeEditor = {};

var Editor = {
  IStandaloneCodeEditor: IStandaloneCodeEditor,
};

export { Language, $$Range, Editor };
/* No side effect */
