// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nprogress from "nprogress";

function actuallyConfigure() {
  Nprogress.configure({
    minimum: 0.08,
    easing: "linear",
    speed: 200,
    trickle: true,
    trickleSpeed: 200,
    showSpinner: false,
  });
}

export { actuallyConfigure };
/* nprogress Not a pure module */
