// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as IntegrationDocsPage from "./IntegrationDocsPage.bs.js";

function CustomIntegrationPage(props) {
  var markAsDone = props.markAsDone;
  var currentRoute = props.currentRoute;
  var tmp;
  switch (currentRoute) {
    case "OnboardingDefault":
      tmp = null;
      break;
    case "WooCommercePlugin":
      tmp = React.createElement(IntegrationDocsPage.make, {
        currentRoute: currentRoute,
        markAsDone: markAsDone,
        languageSelection: false,
      });
      break;
    default:
      tmp = React.createElement(IntegrationDocsPage.make, {
        currentRoute: currentRoute,
        markAsDone: markAsDone,
      });
  }
  return React.createElement(
    "div",
    {
      className: "w-full h-full flex items-center justify-center",
    },
    tmp,
  );
}

var make = CustomIntegrationPage;

export { make };
/* react Not a pure module */
