[default]
check-filename = true
extend-ignore-re = [
    "-nd_[a-zA-Z0-9_-]+",
    "\\bnd[-_][a-zA-Z0-9_-]+"  # matches nd-alert-triangle-outline, nd_gray-100
]

[default.extend-identifiers]
ABD = "ABD"  # Aberdeenshire, UK ISO 3166-2 code
ACTIVITE = "ACTIVITE" # French translation of activity
AER = "AER" # An alias to Api Error Response
ANG = "ANG" # Netherlands Antillean guilder currency code
BA = "BA"  # Bosnia and Herzegovina country code
bottm = "bottm" # name of a css class for nexinets ui test
CAF = "CAF"  # Central African Republic country code
FO = "FO"  # Faroe Islands (the) country code
flate2 = "flate2"
hd = "hd" # animation data parameter
HypoNoeLbFurNiederosterreichUWien = "HypoNoeLbFurNiederosterreichUWien"
hypo_noe_lb_fur_niederosterreich_u_wien = "hypo_noe_lb_fur_niederosterreich_u_wien"
IOT = "IOT" # British Indian Ocean Territory country code
klick = "klick" # Swedish word for clicks
LSO = "LSO" # Lesotho country code
NAM = "NAM"  # Namibia country code
ND = "ND"  # North Dakota state code
optin = "optin" # Boku preflow name
optin_id = "optin_id" # Boku's id for optin flow
passord = "passord" # name of a css class for adyen ui test
payment_vas = "payment_vas"
PaymentVas = "PaymentVas"
PN = "PN" # Pitcairn country code
RegioBank = "RegioBank"
RO = "RO"  # Romania country code
skip_ws = "skip_ws" # skip white space
SOM = "SOM"  # Somalia country code
SUR = "SUR"  # Single South American currency code
THA = "THA"  # Thailand country code
TTO = "TTO" # Trinidad and Tobago country code
WS = "WS" # Samoa country code
ws = "ws" # Web socket
ws2ipdef = "ws2ipdef" # WinSock Extension
ws2tcpip = "ws2tcpip" # WinSock Extension
ZAR = "ZAR"  # South African Rand currency code
JOD = "JOD" # Jordan currency code
