// Generated by ReScript, PLEASE EDIT WITH CARE

function getTimeZoneData(timeZoneType) {
  switch (timeZoneType) {
    case "GMT":
      return {
        offset: "+00:00",
        region: "Africa/Abidjan",
        title: "GMT",
      };
    case "EAT":
      return {
        offset: "+03:00",
        region: "Africa/Addis_Ababa",
        title: "EAT",
      };
    case "CET":
      return {
        offset: "+01:00",
        region: "Africa/Algiers",
        title: "CET",
      };
    case "WAT":
      return {
        offset: "+01:00",
        region: "Africa/Bangui",
        title: "WAT",
      };
    case "CAT":
      return {
        offset: "+02:00",
        region: "Africa/Blantyre",
        title: "CAT",
      };
    case "EET":
      return {
        offset: "+02:00",
        region: "Africa/Cairo",
        title: "EET",
      };
    case "CEST":
      return {
        offset: "+02:00",
        region: "Africa/Ceuta",
        title: "CEST",
      };
    case "SAST":
      return {
        offset: "+02:00",
        region: "Africa/Johannesburg",
        title: "SAST",
      };
    case "HDT":
      return {
        offset: "-09:00",
        region: "America/Adak",
        title: "HDT",
      };
    case "AKDT":
      return {
        offset: "-08:00",
        region: "America/Anchorage",
        title: "AKDT",
      };
    case "AST":
      return {
        offset: "-04:00",
        region: "America/Anguilla",
        title: "AST",
      };
    case "EST":
      return {
        offset: "-05:00",
        region: "America/Atikokan",
        title: "EST",
      };
    case "CDT":
      return {
        offset: "-05:00",
        region: "America/Bahia_Banderas",
        title: "CDT",
      };
    case "CST":
      return {
        offset: "-06:00",
        region: "America/Belize",
        title: "CST",
      };
    case "MDT":
      return {
        offset: "-06:00",
        region: "America/Boise",
        title: "MDT",
      };
    case "MST":
      return {
        offset: "-07:00",
        region: "America/Creston",
        title: "MST",
      };
    case "EDT":
      return {
        offset: "-04:00",
        region: "America/Detroit",
        title: "EDT",
      };
    case "ADT":
      return {
        offset: "-03:00",
        region: "America/Glace_Bay",
        title: "ADT",
      };
    case "PDT":
      return {
        offset: "-07:00",
        region: "America/Los_Angeles",
        title: "PDT",
      };
    case "NDT":
      return {
        offset: "-02:30",
        region: "America/St_Johns",
        title: "NDT",
      };
    case "AEST":
      return {
        offset: "+10:00",
        region: "Antarctica/Macquarie",
        title: "AEST",
      };
    case "NZST":
      return {
        offset: "+12:00",
        region: "Antarctica/McMurdo",
        title: "NZST",
      };
    case "EEST":
      return {
        offset: "+03:00",
        region: "Asia/Amman",
        title: "EEST",
      };
    case "HKT":
      return {
        offset: "+08:00",
        region: "Asia/Hong_Kong",
        title: "HKT",
      };
    case "WIB":
      return {
        offset: "+07:00",
        region: "Asia/Jakarta",
        title: "WIB",
      };
    case "WIT":
      return {
        offset: "+09:00",
        region: "Asia/Jayapura",
        title: "WIT",
      };
    case "IDT":
      return {
        offset: "+03:00",
        region: "Asia/Jerusalem",
        title: "IDT",
      };
    case "PKT":
      return {
        offset: "+05:00",
        region: "Asia/Karachi",
        title: "PKT",
      };
    case "IST":
      return {
        offset: "+05:30",
        region: "Asia/Kolkata",
        title: "IST",
      };
    case "WITA":
      return {
        offset: "+08:00",
        region: "Asia/Makassar",
        title: "WITA",
      };
    case "PST":
      return {
        offset: "+08:00",
        region: "Asia/Manila",
        title: "PST",
      };
    case "KST":
      return {
        offset: "+09:00",
        region: "Asia/Pyongyang",
        title: "KST",
      };
    case "JST":
      return {
        offset: "+09:00",
        region: "Asia/Tokyo",
        title: "JST",
      };
    case "WEST":
      return {
        offset: "+01:00",
        region: "Atlantic/Canary",
        title: "WEST",
      };
    case "ACST":
      return {
        offset: "+09:30",
        region: "Australia/Adelaide",
        title: "ACST",
      };
    case "AWST":
      return {
        offset: "+08:00",
        region: "Australia/Perth",
        title: "AWST",
      };
    case "BST":
      return {
        offset: "+01:00",
        region: "Europe/Guernsey",
        title: "BST",
      };
    case "MSK":
      return {
        offset: "+03:00",
        region: "Europe/Moscow",
        title: "MSK",
      };
    case "ChST":
      return {
        offset: "+10:00",
        region: "Pacific/Guam",
        title: "ChST",
      };
    case "HST":
      return {
        offset: "-10:00",
        region: "Pacific/Honolulu",
        title: "HST",
      };
    case "SST":
      return {
        offset: "-11:00",
        region: "Pacific/Midway",
        title: "SST",
      };
    case "UTC":
      return {
        offset: "+00:00",
        region: "UTC",
        title: "UTC",
      };
  }
}

export { getTimeZoneData };
/* No side effect */
