open ConnectorTypes

let connectorListForLive: array<connectorTypes> = [
  Processors(ADYEN),
  Processors(AUTHORIZEDOTNET),
  Processors(PAYPAL),
  Processors(BANKOFAMERICA),
  Processors(BLUESNAP),
  Processors(BAMBORA),
  Processors(BRAINTREE),
  Processors(CHECKOUT),
  Processors(CRYPTOPAY),
  Processors(CASHTOCODE),
  Processors(CYBERSOURCE),
  Processors(FIUU),
  Processors(IATAPAY),
  Processors(KLARNA),
  Processors(MIFINITY),
  Processors(NMI),
  Processors(NOVALNET),
  Processors(PAYME),
  Processors(TRUSTPAY),
  Processors(VOLT),
  Processors(ZSL),
  Processors(ZEN),
  Processors(PAYBOX),
]