type entityName =
  | CONNECTOR
  | ROUTING
  | MERCHANT_ACCOUNT
  | UPDATE_ORGANIZATION
  | REFUNDS
  | REFUND_FILTERS
  | DISPUTES
  | DISPUTE_FILTERS
  | PAYOUTS
  | PAYOUTS_FILTERS
  | ANALYTICS_FILTERS
  | ANALYTICS_PAYMENTS
  | ANALYTICS_DISPUTES
  | ANALYTICS_REFUNDS
  | ANALYTICS_AUTHENTICATION
  | ANALYTICS_AUTHENTICATION_V2
  | ANALYTICS_AUTHENTICATION_V2_FILTERS
  | API_KEYS
  | ORDERS
  | ORDER_FILTERS
  | ORDERS_AGGREGATE
  | REFUNDS_AGGREGATE
  | DISPUTES_AGGREGATE
  | DEFAULT_FALLBACK
  | SDK_EVENT_LOGS
  | WEBHOOK_EVENTS
  | WEBHOOK_EVENTS_ATTEMPTS
  | WEBHOOKS_EVENTS_RETRY
  | WEBHOOKS_EVENT_LOGS
  | CONNECTOR_EVENT_LOGS
  | GENERATE_SAMPLE_DATA
  | USERS
  | RECON
  | INTEGRATION_DETAILS
  | FRAUD_RISK_MANAGEMENT
  | USER_MANAGEMENT
  | THREE_DS
  | BUSINESS_PROFILE
  | VERIFY_APPLE_PAY
  | PAYMENT_REPORT
  | REFUND_REPORT
  | DISPUTE_REPORT
  | AUTHENTICATION_REPORT
  | PAYPAL_ONBOARDING
  | PAYPAL_ONBOARDING_SYNC
  | ACTION_URL
  | RESET_TRACKING_ID
  | SURCHARGE
  | CUSTOMERS
  | PAYMENT_METHODS
  | PAYMENT_METHODS_DETAILS
  | ACCEPT_DISPUTE
  | DISPUTES_ATTACH_EVIDENCE
  | PAYOUT_DEFAULT_FALLBACK
  | PAYOUT_ROUTING
  | ACTIVE_PAYOUT_ROUTING
  | ACTIVE_ROUTING
  | ENABLE_AUTH_RATE_ROUTING
  | SET_CONFIG_AUTH_RATE_ROUTING
  | ACTIVATE_AUTH_RATE_ROUTING
  | SET_VOLUME_SPLIT
  | GET_VOLUME_SPLIT
  | GLOBAL_SEARCH
  | PAYMENT_METHOD_CONFIG
  | API_EVENT_LOGS
  | ANALYTICS_PAYMENTS_V2
  | ANALYTICS_SANKEY
  | HYPERSENSE
  | SIMULATE_INTELLIGENT_ROUTING
  | INTELLIGENT_ROUTING_RECORDS
  | INTELLIGENT_ROUTING_GET_STATISTICS
  | SDK_PAYMENT
  | GET_REVIEW_FIELDS
  | TRANSACTION_OVERVIEW
  | RETRY_PERFORMANCE
  | MONTHLY_RETRY_SUCCESS
  | RETRY_ATTEMPTS_TREND
  | ERROR_CATEGORY_ANALYSIS
  | RECOVERY_INVOICES
  | RECOVERY_ATTEMPTS

type v2entityNameType =
  | CUSTOMERS
  | V2_CONNECTOR
  | V2_ORDERS_LIST
  | PAYMENT_METHOD_LIST
  | RETRIEVE_PAYMENT_METHOD
  | V2_ORDER_FILTERS
  | USERS
  | TOTAL_TOKEN_COUNT
  | MERCHANT_ACCOUNT

type userRoleTypes = USER_LIST | ROLE_LIST | ROLE_ID | NONE

type reconType = [#TOKEN | #REQUEST | #NONE]
type hypersenseType = [#TOKEN | #HOME | #NONE]

type userType = [
  | #CONNECT_ACCOUNT
  | #SIGNUP
  | #SIGNINV2
  | #SIGNOUT
  | #FORGOT_PASSWORD
  | #RESET_PASSWORD
  | #VERIFY_EMAIL_REQUEST
  | #VERIFY_EMAILV2
  | #ACCEPT_INVITE_FROM_EMAIL
  | #SET_METADATA
  | #GROUP_ACCESS_INFO
  | #ROLE_INFO
  | #MERCHANT_DATA
  | #USER_DATA
  | #USER_DELETE
  | #USER_UPDATE
  | #UPDATE_ROLE
  | #INVITE_MULTIPLE
  | #RESEND_INVITE
  | #CREATE_ORG
  | #CREATE_MERCHANT
  | #GET_GROUP_ACL
  | #CREATE_CUSTOM_ROLE
  | #FROM_EMAIL
  | #USER_INFO
  | #ROTATE_PASSWORD
  | #BEGIN_TOTP
  | #VERIFY_TOTP
  | #VERIFY_RECOVERY_CODE
  | #GENERATE_RECOVERY_CODES
  | #TERMINATE_TWO_FACTOR_AUTH
  | #CHECK_TWO_FACTOR_AUTH_STATUS
  | #RESET_TOTP
  | #GET_AUTH_LIST
  | #AUTH_SELECT
  | #SIGN_IN_WITH_SSO
  | #CHANGE_PASSWORD
  | #SWITCH_ORG
  | #SWITCH_MERCHANT_NEW
  | #SWITCH_PROFILE
  | #LIST_ORG
  | #LIST_MERCHANT
  | #LIST_PROFILE
  | #LIST_ROLES_FOR_INVITE
  | #SWITCH_ORG
  | #SWITCH_PROFILE
  | #ROLE_INFO
  | #LIST_INVITATION
  | #ACCEPT_INVITATION_PRE_LOGIN
  | #USER_DETAILS
  | #LIST_ROLES_FOR_ROLE_UPDATE
  | #ACCEPT_INVITATION_HOME
  | #CHECK_TWO_FACTOR_AUTH_STATUS_V2
  | #NONE
]

type entityTypeWithVersion = V1(entityName) | V2(v2entityNameType)

type getUrlTypes = (
  ~entityName: entityTypeWithVersion,
  ~methodType: Fetch.requestMethod,
  ~id: option<string>=?,
  ~connector: option<string>=?,
  ~userType: userType=?,
  ~userRoleTypes: userRoleTypes=?,
  ~reconType: reconType=?,
  ~hypersenseType: hypersenseType=?,
  ~queryParamerters: option<string>=?,
) => string
