// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Recoil from "../../libraries/Recoil.bs.js";

var customFilterAtom = Recoil.atom("customFilterAtom", "");

var completionProvider = Recoil.atom("completionProvider", undefined);

export { customFilterAtom, completionProvider };
/* customFilterAtom Not a pure module */
