// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as APIUtils from "../APIUtils/APIUtils.bs.js";
import * as LogicUtils from "../../utils/LogicUtils.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as LoadedTable from "../../components/LoadedTable.bs.js";
import * as RolesEntity from "./RolesEntity.bs.js";
import * as PageLoaderWrapper from "../Helpers/PageLoaderWrapper.bs.js";

function RoleListTableView(props) {
  var getURL = APIUtils.useGetURL();
  var fetchDetails = APIUtils.useGetMethod(undefined, undefined);
  var match = React.useState(function () {
    return "Loading";
  });
  var setScreenStateRoles = match[1];
  var match$1 = React.useState(function () {
    return [];
  });
  var setRolesAvailableData = match$1[1];
  var rolesAvailableData = match$1[0];
  var match$2 = React.useState(function () {
    return 0;
  });
  var getRolesAvailable = async function () {
    setScreenStateRoles(function (param) {
      return "Loading";
    });
    try {
      var userDataURL = getURL(
        "USER_MANAGEMENT",
        "Get",
        undefined,
        undefined,
        undefined,
        "ROLE_LIST",
        undefined,
        undefined,
        undefined,
      );
      var res = await fetchDetails(userDataURL + "?groups=true");
      var rolesData = LogicUtils.getArrayDataFromJson(
        res,
        RolesEntity.itemToObjMapperForRoles,
      );
      setRolesAvailableData(function (param) {
        return rolesData.map(function (prim) {
          return prim;
        });
      });
      return setScreenStateRoles(function (param) {
        return "Success";
      });
    } catch (exn) {
      return setScreenStateRoles(function (param) {
        return {
          TAG: "Error",
          _0: "",
        };
      });
    }
  };
  React.useEffect(function () {
    if (rolesAvailableData.length === 0) {
      getRolesAvailable();
    } else {
      setScreenStateRoles(function (param) {
        return "Success";
      });
    }
  }, []);
  return React.createElement(
    "div",
    {
      className: "mt-5",
    },
    React.createElement(PageLoaderWrapper.make, {
      children: Caml_option.some(
        React.createElement(LoadedTable.make, {
          title: "Roles",
          showSerialNumber: true,
          actualData: rolesAvailableData,
          totalResults: rolesAvailableData.length,
          resultsPerPage: 10,
          offset: match$2[0],
          setOffset: match$2[1],
          entity: RolesEntity.rolesEntity,
          currrentFetchCount: rolesAvailableData.length,
          hideTitle: true,
          tableheadingClass: "h-12",
          collapseTableRow: false,
        }),
      ),
      screenState: match[0],
    }),
  );
}

var make = RoleListTableView;

export { make };
/* react Not a pure module */
