name: Adding New Connector Issue Template
about: Create multiple related issues regarding new connector addition in dashboard
title: "[FEAT]: Add New Connector"
labels: ["core", "S-awaiting-triage"]
body:
  - type: dropdown
    id: category-of-connector
    attributes:
      label: What is the category of connector that is to be added?
      description: Choose one of the below categories.
      options:
        - Payment Connector
        - Payout Connector
        - Payment Method Authentication Connector
        - Tax Connector
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Sub-tasks

        - [ ] [Integrate connector in dashboard](https://github.com/juspay/hyperswitch-control-center/issues/new?title=Integrate+connector+in+dashboard&labels=task)

        - [ ] [Add icon for connector according to existing standards](https://github.com/juspay/hyperswitch-control-center/issues/new?title=Add+icon+for+connector+according+to+existing+standards&labels=task)

        - [ ] [Update frontend wasm according to latest wasm in backend](https://github.com/juspay/hyperswitch-control-center/issues/new?title=Update+frontend+wasm+according+to+latest+wasm+in+backend&labels=task)

  - type: markdown
    attributes:
      value: |
        ### Instructions:
        
        1. For each sub-task, click the corresponding link to automatically open an issue with pre-filled content.
        2. Once you've created an issue, check the box next to the task to track progress.
