name: Integrating new connector
description: Submit a request to integrate new connector
title: "[FEAT]: Integrate New Connector <connector_name>"
labels: ["core", "S-awaiting-triage"]
body:
  - type: textarea
    id: connector-category
    attributes:
      label: Connector Category
      description: Enter the category to which the new connector belongs.
      placeholder: Payment Processor
    validations:
      required: true

  - type: textarea
    id: connector-description
    attributes:
      label: Connector Description
      description: Enter the connector description to be displayed on dashboard.
      placeholder: The above connector enables...
    validations:
      required: true

  - type: markdown
    id: creating-subtasks
    attributes:
      value: |
        ### Sub-tasks

        - [ ] [[FEAT]: Integrate the connector in dashboard](https://github.com/juspay/hyperswitch-control-center/issues/new?title=%5BFEAT%5D%3A+Integrate+the+connector+in+dashboard&labels=core,S-awaiting-triage)

        - [ ] [[FEAT]: Add icon for connector as per existing standards](https://github.com/juspay/hyperswitch-control-center/issues/new?title=%5BFEAT%5D%3A+Add+icon+for+connector+as+per+existing+standards&labels=core,S-awaiting-triage)

        - [ ] [[FEAT]: Update frontend wasm as per latest wasm in backend](https://github.com/juspay/hyperswitch-control-center/issues/new?title=%5BFEAT%5D%3A+Update+frontend+wasm+as+per+latest+wasm+in+backend&labels=core,S-awaiting-triage)

  - type: markdown
    id: instructions
    attributes:
      value: |
        ### Instructions:

        1. For each sub-task, click the corresponding link to automatically open an issue with pre-filled content.
        2. Once you've created an issue, check the box next to the task to track progress.
