type paymentLifeCycle = {
  normal_success: int,
  normal_failure: int,
  cancelled: int,
  smart_retried_success: int,
  smart_retried_failure: int,
  pending: int,
  partial_refunded: int,
  refunded: int,
  disputed: int,
  pm_awaited: int,
  customer_awaited: int,
  merchant_awaited: int,
  confirmation_awaited: int,
}
