// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "../../../../components/Button.bs.js";
import * as LogicUtils from "../../../../utils/LogicUtils.bs.js";
import * as FormRenderer from "../../../../components/form/FormRenderer.bs.js";
import * as ReactFinalForm from "../../../../libraries/ReactFinalForm.bs.js";
import * as ReactFinalForm$1 from "react-final-form";
import * as CommonMetaDataUtils from "../Common/CommonMetaDataUtils.bs.js";
import * as ApplePayIntegrationUtils from "./ApplePayIntegrationUtils.bs.js";
import * as ApplePayIntegrationHelper from "./ApplePayIntegrationHelper.bs.js";

function ApplePayZen(props) {
  var setShowWalletConfigurationModal = props.setShowWalletConfigurationModal;
  var closeModal = props.closeModal;
  var update = props.update;
  var form = ReactFinalForm$1.useForm();
  var formState = ReactFinalForm$1.useFormState(
    ReactFinalForm.useFormSubscription(["values"]),
  );
  var initalFormValue = LogicUtils.getDictfromDict(
    LogicUtils.getDictfromDict(
      LogicUtils.getDictFromJsonObject(formState.values),
      "metadata",
    ),
    "apple_pay",
  );
  var setFormData = function () {
    var value = ApplePayIntegrationUtils.zenApplePayConfig(initalFormValue);
    form.change("metadata.apple_pay", value);
  };
  React.useEffect(function () {
    setFormData();
  }, []);
  var onSubmit = function () {
    var metadata = LogicUtils.getDictfromDict(
      LogicUtils.getDictFromJsonObject(formState.values),
      "metadata",
    );
    update(metadata);
    setShowWalletConfigurationModal(function (param) {
      return false;
    });
    return Promise.resolve(null);
  };
  var applePayManualFields = props.applePayFields.map(function (field, index) {
    var applePayField = CommonMetaDataUtils.inputFieldMapper(
      LogicUtils.convertMapObjectToDict(field),
    );
    return React.createElement(
      "div",
      {
        key: index.toString(),
      },
      React.createElement(FormRenderer.FieldRenderer.make, {
        field: ApplePayIntegrationHelper.applePayValueInput(
          applePayField,
          undefined,
          undefined,
        ),
        labelClass: "font-semibold !text-hyperswitch_black",
      }),
    );
  });
  return React.createElement(
    React.Fragment,
    {},
    applePayManualFields,
    React.createElement(
      "div",
      {
        className: "w-full flex gap-2 justify-end p-6",
      },
      React.createElement(Button.make, {
        text: "Go Back",
        buttonType: "Secondary",
        onClick: function (_ev) {
          closeModal();
        },
      }),
      React.createElement(Button.make, {
        buttonState: ApplePayIntegrationUtils.validateZenFlow(formState.values),
        text: "Verify & Enable",
        buttonType: "Primary",
        onClick: function (_ev) {
          onSubmit();
        },
      }),
    ),
  );
}

var make = ApplePayZen;

export { make };
/* react Not a pure module */
