type steps =
  | Checkout
  | Configurator

type paymentLinkWasmPayload = {
  amount: string,
  currency: string,
  pub_key: string,
  client_secret: string,
  payment_id: string,
  session_expiry: string,
  merchant_logo: string,
  return_url: string,
  merchant_name: string,
  max_items_visible_after_collapse: int,
  theme: string,
  merchant_description: option<string>,
  sdk_layout: string,
  display_sdk_only: bool,
  hide_card_nickname_field: bool,
  show_card_form_by_default: bool,
  locale: option<string>,
  background_image: option<string>,
  details_layout: option<string>,
  branding_visibility: option<bool>,
  payment_button_text: option<string>,
  skip_status_screen: option<bool>,
  custom_message_for_card_terms: option<string>,
  payment_button_colour: option<string>,
  payment_button_text_colour: option<string>,
  background_colour: option<string>,
  sdk_ui_rules: option<JSON.t>,
  status: string,
  enable_button_only_on_form_ready: bool,
  payment_form_header_text: option<string>,
  payment_form_label_type: option<string>,
  show_card_terms: option<string>,
  is_setup_mandate_flow: option<bool>,
  capture_method: option<string>,
  setup_future_usage_applied: option<string>,
  color_icon_card_cvc_error: option<string>,
}
