// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Recoil from "../libraries/Recoil.bs.js";
import * as Recoil$1 from "recoil";

var defaultOpenPopUp = [];

var openPopUp = Recoil.atom("openPopUp", defaultOpenPopUp);

function useShowPopUp() {
  var setOpenPopUp = Recoil$1.useSetRecoilState(openPopUp);
  return React.useCallback(
    function (popUpProps) {
      setOpenPopUp(function (prevArr) {
        return prevArr.concat([popUpProps]);
      });
    },
    [setOpenPopUp],
  );
}

export { defaultOpenPopUp, openPopUp, useShowPopUp };
/* openPopUp Not a pure module */
