// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "../../../components/Button.bs.js";
import * as GoLive from "./GoLive.bs.js";
import * as GlobalVars from "../../../utils/GlobalVars.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as GlobalProvider from "../../../entryPoints/Provider/GlobalProvider.bs.js";
import * as QuickStartUIUtils from "./QuickStartUIUtils.bs.js";
import * as ConfigureConnector from "../CommonConnectorFlow/ConfigureConnector.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as IntegrateYourAppLanding from "./IntegrateYourApp/IntegrateYourAppLanding.bs.js";

function ConfigureControlCenter(props) {
  var match = React.useContext(GlobalProvider.defaultContext);
  var quickStartPageState = match.quickStartPageState;
  var setDashboardPageState = match.setDashboardPageState;
  var landingButtonGroup = React.createElement(
    "div",
    {
      className: "flex flex-col gap-4 w-full",
    },
    React.createElement(Button.make, {
      text: "Go to Home",
      buttonType: "Primary",
      onClick: function (param) {
        setDashboardPageState(function (param) {
          return "HOME";
        });
        RescriptReactRouter.replace(GlobalVars.appendDashboardPath("/home"));
      },
    }),
  );
  var tmp;
  if (typeof quickStartPageState !== "object") {
    tmp = React.createElement(
      "div",
      {
        className: "h-screen flex items-center justify-center",
      },
      React.createElement(QuickStartUIUtils.StepCompletedPage.make, {
        buttonGroup: Caml_option.some(landingButtonGroup),
        headerText: "Yay! you have successfully completed the setup!",
      }),
    );
  } else {
    switch (quickStartPageState.TAG) {
      case "ConnectProcessor":
        tmp = React.createElement(ConfigureConnector.make, {
          connectProcessorValue: quickStartPageState._0,
        });
        break;
      case "IntegrateApp":
        tmp = React.createElement(IntegrateYourAppLanding.make, {
          integrateAppValue: quickStartPageState._0,
        });
        break;
      case "GoLive":
        tmp = React.createElement(GoLive.make, {
          goLive: quickStartPageState._0,
        });
        break;
    }
  }
  return React.createElement(
    "div",
    {
      className: "h-screen w-full bg-blue-background_blue",
    },
    tmp,
  );
}

var make = ConfigureControlCenter;

export { make };
/* react Not a pure module */
