[default.theme]
primary_color="#006DF9"
primary_hover_color="#005ED6"
sidebar_color="#242F48"
[default.endpoints]
api_url="https://app.hyperswitch.io"
sdk_url=""
[default.features]
test_live_toggle=false
is_live_mode=false
email=false
quick_start=true
audit_trail=false
system_metrics=false
sample_data=false
frm=false
payout=true
recon=false
test_processors=true
feedback=false
mixpanel=false
generate_report=false
user_journey_analytics=false
surcharge=false
dispute_evidence_upload=false
paypal_automatic_flow=false
threeds_authenticator=false
global_search=false
dispute_analytics=false
configure_pmts=false

[zurich.theme]
primary_color="#006DF9"
primary_hover_color="#005ED6"
sidebar_color="#248"
