[default.theme]
primary_color="#006DF9"
primary_hover_color="#005ED6"
sidebar_color="#242F48"
[default.endpoints]
api_url="http://localhost:8080"
sdk_url="http://localhost:9050/HyperLoader.js"
logo_url=""
favicon_url=""
agreement_url=""
agreement_version=""
apple_pay_certificate_url=""
mixpanel_token=""
recon_iframe_url=""
dss_certificate_url=""
[default.features]
test_live_toggle=false
is_live_mode=false
email=false
quick_start=false
audit_trail=false
system_metrics=false
sample_data=false
frm=false
payout=true
recon=false
test_processors=true
feedback=false
mixpanel=false
generate_report=false
user_journey_analytics=false
authentication_analytics=false
surcharge=false
dispute_evidence_upload=false
paypal_automatic_flow=false
threeds_authenticator=false
global_search=false
dispute_analytics=false
configure_pmts=false
branding=false
live_users_counter=false
granularity=false
custom_webhook_headers=false
compliance_certificate=false
pm_authentication_processor=true
performance_monitor=false
new_analytics=false
down_time=false
tax_processor=true
transaction_view=false
x_feature_route=false
[default.merchant_config]
[default.merchant_config.new_analytics]
org_ids=[]
merchant_ids=[]
profile_ids=[]
