[default.endpoints]
api_url="http://localhost:9000/api"
sdk_url="http://localhost:9050/HyperLoader.js"
apple_pay_certificate_url=""
dss_certificate_url=""
logo_url=""
favicon_url=""
recon_iframe_url=""
hypersense_url=""
mixpanel_token=""
agreement_url=""
agreement_version=""
[default.features]
branding=false
mixpanel=false
test_live_toggle=false
is_live_mode=false
feedback=false
x_feature_route=false
compliance_certificate=false
force_cookies=false
audit_trail=true
granularity=false
maintainence_alert=""
down_time=false
email=false
totp=true
quick_start=false
global_search=false
global_search_filters=false
sample_data=false
generate_report=false
transaction_view=true
configure_pmts=true
test_processors=true
paypal_automatic_flow=false
payout=true
threeds_authenticator=true
frm=true
pm_authentication_processor=true
tax_processor=true
dispute_analytics=false
authentication_analytics=false
performance_monitor=false
new_analytics=false
new_analytics_smart_retries=false
new_analytics_refunds=false
new_analytics_filters=false
surcharge=true
dispute_evidence_upload=false
recon=true
recon_v2=false
custom_webhook_headers=true
tenant_user=false
dev_click_to_pay=true
dev_recovery_v2_product=false
dev_vault_v2_product=false
dev_modularity_v2=false
dev_alt_payment_methods=false
dev_hypersense_v2_product=false
dev_intelligent_routing_v2=false
dev_recon_v2_product=false
dev_debit_routing=false
google_pay_decryption_flow=false
dev_webhooks=false
[default.merchant_config]
[default.merchant_config.new_analytics]
org_ids=[]
merchant_ids=[]
profile_ids=[]
