let reportsResponse = {
  "data": [
    {
      "transaction_id": "Txn_1234",
      "order_id": "Ord_5678",
      "payment_gateway": "Stripe",
      "payment_method": "Credit Card",
      "txn_amount": 324.0,
      "settlement_amount": 324.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1235",
      "order_id": "Ord_5679",
      "payment_gateway": "Stripe",
      "payment_method": "Credit Card",
      "txn_amount": 221.0,
      "settlement_amount": 180.0,
      "recon_status": "Unreconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1236",
      "order_id": "Ord_5680",
      "payment_gateway": "Stripe",
      "payment_method": "Credit Card",
      "txn_amount": 801.0,
      "settlement_amount": 801.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1237",
      "order_id": "Ord_5681",
      "payment_gateway": "Stripe",
      "payment_method": "Debit Card",
      "txn_amount": 831.0,
      "settlement_amount": 820.0,
      "recon_status": "Unreconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1238",
      "order_id": "Ord_5682",
      "payment_gateway": "Stripe",
      "payment_method": "Wallet",
      "txn_amount": 218.0,
      "settlement_amount": 218.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1239",
      "order_id": "Ord_5683",
      "payment_gateway": "Stripe",
      "payment_method": "Debit Card",
      "txn_amount": 916.0,
      "settlement_amount": 910.0,
      "recon_status": "Unreconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1240",
      "order_id": "Ord_5684",
      "payment_gateway": "Stripe",
      "payment_method": "Credit Card",
      "txn_amount": 507.0,
      "settlement_amount": 507.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1241",
      "order_id": "Ord_5685",
      "payment_gateway": "Stripe",
      "payment_method": "Wallet",
      "txn_amount": 137.0,
      "settlement_amount": 137.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1242",
      "order_id": "Ord_5686",
      "payment_gateway": "Stripe",
      "payment_method": "Credit Card",
      "txn_amount": 808.0,
      "settlement_amount": 808.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1243",
      "order_id": "Ord_5687",
      "payment_gateway": "Stripe",
      "payment_method": "Debit Card",
      "txn_amount": 807.0,
      "settlement_amount": 720.0,
      "recon_status": "Unreconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1244",
      "order_id": "Ord_5688",
      "payment_gateway": "Stripe",
      "payment_method": "Wallet",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1245",
      "order_id": "Ord_5689",
      "payment_gateway": "Stripe",
      "payment_method": "Credit Card",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1246",
      "order_id": "Ord_5690",
      "payment_gateway": "Stripe",
      "payment_method": "Debit Card",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1247",
      "order_id": "Ord_5691",
      "payment_gateway": "Stripe",
      "payment_method": "Wallet",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1248",
      "order_id": "Ord_5692",
      "payment_gateway": "Stripe",
      "payment_method": "Credit Card",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1249",
      "order_id": "Ord_5693",
      "payment_gateway": "Stripe",
      "payment_method": "Wallet",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1250",
      "order_id": "Ord_5694",
      "payment_gateway": "Stripe",
      "payment_method": "Debit Card",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1251",
      "order_id": "Ord_5695",
      "payment_gateway": "Stripe",
      "payment_method": "Credit Card",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1252",
      "order_id": "Ord_5696",
      "payment_gateway": "Stripe",
      "payment_method": "Wallet",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
    {
      "transaction_id": "Txn_1253",
      "order_id": "Ord_5697",
      "payment_gateway": "Stripe",
      "payment_method": "Debit Card",
      "txn_amount": 100.0,
      "settlement_amount": 100.0,
      "recon_status": "Reconciled",
      "transaction_date": "Jan 22 2025 03:25PM",
      "actions": "",
    },
  ],
}->Identity.genericTypeToJson

let reportsExceptionResponse = {
  {
    "data": [
      {
        "transaction_id": "Txn_1235",
        "order_id": "Ord_5679",
        "payment_gateway": "Stripe",
        "payment_method": "Credit Card",
        "txn_amount": 221.0,
        "settlement_amount": 180.0,
        "mismatch_amount": 41.0,
        "recon_status": "Unreconciled",
        "exception_status": "Under Review",
        "exception_type": "Amount Mismatch",
        "transaction_date": "Jan 22 2025 03:25PM",
        "exception_matrix": [
          {
            "source": "Order Source",
            "order_id": "Ord_5679",
            "txn_amount": 221.0,
            "settlement_amount": 180.0,
            "payment_gateway": "Stripe",
            "settlement_date": "Jan 24 2025 07:24PM",
            "fee_amount": 0,
          },
        ],
        "actions": "View",
      },
      {
        "transaction_id": "Txn_1237",
        "order_id": "Ord_5681",
        "payment_gateway": "Stripe",
        "payment_method": "Debit Card",
        "txn_amount": 831.0,
        "settlement_amount": 820.0,
        "mismatch_amount": 11.0,
        "recon_status": "Unreconciled",
        "exception_status": "Under Review",
        "exception_type": "Amount Mismatch",
        "transaction_date": "Jan 22 2025 03:25PM",
        "exception_matrix": [
          {
            "source": "Order Source",
            "order_id": "Ord_5681",
            "txn_amount": 831.0,
            "settlement_amount": 820.0,
            "payment_gateway": "Stripe",
            "settlement_date": "Jan 24 2025 07:24PM",
            "fee_amount": 0,
          },
        ],
        "actions": "View",
      },
      {
        "transaction_id": "Txn_1239",
        "order_id": "Ord_5683",
        "payment_gateway": "Stripe",
        "payment_method": "Debit Card",
        "txn_amount": 916.0,
        "settlement_amount": 910.0,
        "mismatch_amount": 6.0,
        "recon_status": "Unreconciled",
        "exception_status": "Under Review",
        "exception_type": "Amount Mismatch",
        "transaction_date": "Jan 22 2025 03:25PM",
        "exception_matrix": [
          {
            "source": "Order Source",
            "order_id": "Ord_5683",
            "txn_amount": 916.0,
            "settlement_amount": 910.0,
            "payment_gateway": "Stripe",
            "settlement_date": "Jan 24 2025 07:24PM",
            "fee_amount": 0,
          },
        ],
        "actions": "View",
      },
      {
        "transaction_id": "Txn_1243",
        "order_id": "Ord_5687",
        "payment_gateway": "Stripe",
        "payment_method": "Debit Card",
        "txn_amount": 807.0,
        "settlement_amount": 720.0,
        "mismatch_amount": 87.0,
        "recon_status": "Unreconciled",
        "exception_status": "Under Review",
        "exception_type": "Amount Mismatch",
        "transaction_date": "Jan 22 2025 03:25PM",
        "exception_matrix": [
          {
            "source": "Order Source",
            "order_id": "Ord_5687",
            "txn_amount": 807.0,
            "settlement_amount": 720.0,
            "payment_gateway": "Stripe",
            "settlement_date": "Jan 24 2025 07:24PM",
            "fee_amount": 0,
          },
        ],
        "actions": "View",
      },
    ],
    "total": {
      "total_transactions": 4,
      "total_txn_amount": 2775.0,
      "total_settlement_amount": 2630.0,
      "total_mismatch_amount": 145.0,
    },
  }
}->Identity.genericTypeToJson
