// TODO: This sample data will be removed
let data = {
  "data": [
    {
      "transaction_id": "TXN1001",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 3450,
      "currency": "AUD",
      "status": "expected",
      "created_at": "2025-03-01T10:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1002",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 2999,
      "currency": "AUD",
      "status": "posted",
      "created_at": "2025-03-01T11:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1003",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 7800,
      "currency": "AUD",
      "status": "mismatched",
      "created_at": "2025-03-01T12:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1004",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 4300,
      "currency": "AUD",
      "status": "archived",
      "created_at": "2025-03-02T09:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1005",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 1500,
      "currency": "AUD",
      "status": "expected",
      "created_at": "2025-03-02T10:30:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1006",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 999,
      "currency": "AUD",
      "status": "posted",
      "created_at": "2025-03-02T11:30:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1007",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 6200,
      "currency": "AUD",
      "status": "mismatched",
      "created_at": "2025-03-03T10:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1008",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 4700,
      "currency": "AUD",
      "status": "archived",
      "created_at": "2025-03-03T11:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1009",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 1100,
      "currency": "AUD",
      "status": "expected",
      "created_at": "2025-03-03T12:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1010",
      "credit_account": "life3",
      "debit_account": "adyen",
      "amount": 2700,
      "currency": "AUD",
      "status": "posted",
      "created_at": "2025-03-04T09:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1011",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 5000,
      "currency": "AUD",
      "status": "mismatched",
      "created_at": "2025-03-04T10:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1012",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 3500,
      "currency": "AUD",
      "status": "archived",
      "created_at": "2025-03-04T11:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1013",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 4100,
      "currency": "AUD",
      "status": "expected",
      "created_at": "2025-03-05T09:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1014",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 3000,
      "currency": "AUD",
      "status": "posted",
      "created_at": "2025-03-05T10:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1015",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 2750,
      "currency": "AUD",
      "status": "mismatched",
      "created_at": "2025-03-05T11:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1016",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 4600,
      "currency": "AUD",
      "status": "archived",
      "created_at": "2025-03-06T09:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1017",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 3900,
      "currency": "AUD",
      "status": "expected",
      "created_at": "2025-03-06T10:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1018",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 2100,
      "currency": "AUD",
      "status": "posted",
      "created_at": "2025-03-06T11:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1019",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 3100,
      "currency": "AUD",
      "status": "mismatched",
      "created_at": "2025-03-07T09:00:00",
      "variance": 0,
    },
    {
      "transaction_id": "TXN1020",
      "credit_account": "adyen",
      "debit_account": "anz",
      "amount": 3300,
      "currency": "AUD",
      "status": "archived",
      "created_at": "2025-03-07T10:00:00",
      "variance": 0,
    },
  ],
}->Identity.genericTypeToJson
