// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Clipboard from "../libraries/Clipboard.bs.js";
import * as ReactFinalForm from "react-final-form";

function CopyFieldValue(props) {
  var data = ReactFinalForm.useField(props.fieldkey).input.value;
  return React.createElement(Clipboard.Copy.make, {
    data: data,
  });
}

var make = CopyFieldValue;

export { make };
/* react Not a pure module */
