// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as LogicUtils from "../utils/LogicUtils.bs.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";

function parseFilterString(queryString) {
  return Object.fromEntries(
    Belt_Array.keepMap(decodeURI(queryString).split("&"), function (str) {
      var arr = str.split("=");
      var key = Core__Option.getOr(arr[0], "-");
      var val = arr.slice(1).join("=");
      if (LogicUtils.isEmptyString(key) || LogicUtils.isEmptyString(val)) {
        return;
      } else {
        return [key, val];
      }
    }),
  );
}

function parseFilterDict(dict) {
  return Object.entries(dict)
    .map(function (item) {
      return item[0] + "=" + item[1];
    })
    .join("&");
}

export { parseFilterString, parseFilterDict };
/* LogicUtils Not a pure module */
