// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as AddDataAttributes from "./AddDataAttributes.bs.js";

function Icon(props) {
  var customHeight = props.customHeight;
  var customWidth = props.customWidth;
  var __customIconColor = props.customIconColor;
  var parentClass = props.parentClass;
  var onClick = props.onClick;
  var className = props.className;
  var __size = props.size;
  var name = props.name;
  var size = __size !== undefined ? __size : 20;
  var customIconColor =
    __customIconColor !== undefined ? __customIconColor : "";
  var useUrl = React.createElement("use", {
    className: "fill-current " + customIconColor,
    xlinkHref: "/icons/solid.svg#" + name,
  });
  var otherClasses = className !== undefined ? className : "";
  var handleClick = function (ev) {
    if (onClick !== undefined) {
      return onClick(ev);
    }
  };
  return React.createElement(AddDataAttributes.make, {
    attributes: [["data-icon", name]],
    children: React.createElement(
      "div",
      {
        className:
          parentClass !== undefined
            ? parentClass
            : "flex flex-col justify-center",
      },
      React.createElement(
        "svg",
        {
          className: "fill-current " + otherClasses,
          height:
            (Core__Option.isSome(customHeight)
              ? Core__Option.getOr(customHeight, "")
              : size.toString()) + "px",
          width:
            (Core__Option.isSome(customWidth)
              ? Core__Option.getOr(customWidth, "")
              : size.toString()) + "px",
          onClick: handleClick,
          fill: customIconColor,
        },
        useUrl,
      ),
    ),
  });
}

var make = Icon;

export { make };
/* react Not a pure module */
