// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as InfraCalendar from "./InfraCalendar.bs.js";
import * as JsxPPXReactSupportU from "rescript/lib/es6/jsxPPXReactSupportU.js";

var startYear = {
  contents: 2016,
};

var years = [];

while ((new Date().getFullYear() | 0) >= startYear.contents) {
  years.push(startYear.contents);
  startYear.contents = (startYear.contents + 1) | 0;
}

years.reverse();

var months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

function getMonthInStr(mon) {
  switch (mon) {
    case "Jan":
      return "January, ";
    case "Feb":
      return "February, ";
    case "Mar":
      return "March, ";
    case "Apr":
      return "April, ";
    case "May":
      return "May, ";
    case "Jun":
      return "June, ";
    case "Jul":
      return "July, ";
    case "Aug":
      return "August, ";
    case "Sep":
      return "September, ";
    case "Oct":
      return "October, ";
    case "Nov":
      return "November, ";
    case "Dec":
      return "December, ";
  }
}

function getMonthFromFloat(value) {
  var valueInt = value | 0;
  return Core__Option.getOr(months[valueInt], "Jan");
}

function InfraCalendarList$YearItem(props) {
  var tempMonth = props.tempMonth;
  var setCurrDate = props.setCurrDate;
  var handleChangeMonthBy = props.handleChangeMonthBy;
  var year = props.year;
  var tempYear = props.tempYear;
  var isSelected = year === tempYear;
  var yearRef = React.useRef(null);
  React.useEffect(
    function () {
      if (isSelected) {
        var element = yearRef.current;
        if (!(element == null)) {
          element.scrollIntoView();
        }
      }
    },
    [isSelected],
  );
  return React.createElement(
    "li",
    {
      ref: Caml_option.some(yearRef),
      className:
        "p-2 " +
        (year === (tempYear | 0)
          ? "bg-blue-600 text-white"
          : "dark:hover:bg-jp-gray-900 hover:bg-jp-gray-100") +
        " cursor-pointer bg-opacity-100",
      value: year.toString(),
      onClick: function (e) {
        var tar = e.currentTarget.value;
        var yearDiff = (tar - tempYear) | 0;
        if (yearDiff !== 0) {
          handleChangeMonthBy(Math.imul(yearDiff, 12));
          return setCurrDate(function (param) {
            return new Date(tar, tempMonth);
          });
        }
      },
    },
    year.toString(),
  );
}

var YearItem = {
  make: InfraCalendarList$YearItem,
};

function InfraCalendarList$MonthItem(props) {
  var setCurrDate = props.setCurrDate;
  var handleChangeMonthBy = props.handleChangeMonthBy;
  var tempYear = props.tempYear;
  var tempMonth = props.tempMonth;
  var index = props.index;
  var isSelected = index === tempMonth;
  var monthRef = React.useRef(null);
  React.useEffect(
    function () {
      if (isSelected) {
        var element = monthRef.current;
        if (!(element == null)) {
          element.scrollIntoView();
        }
      }
    },
    [isSelected],
  );
  return React.createElement(
    "li",
    {
      ref: Caml_option.some(monthRef),
      className:
        "p-2 px-4 " +
        (index === (tempMonth | 0)
          ? "bg-blue-600 text-white"
          : "dark:hover:bg-jp-gray-900 hover:bg-jp-gray-100") +
        "  cursor-pointer",
      value: index.toString(),
      onClick: function (e) {
        var tar = e.currentTarget.value;
        var monthDiff = (tar - tempMonth) | 0;
        if (monthDiff !== 0) {
          handleChangeMonthBy(monthDiff);
          return setCurrDate(function (param) {
            return new Date(tempYear, tar);
          });
        }
      },
    },
    getMonthInStr(props.mon).replace(/,/g, ""),
  );
}

var MonthItem = {
  make: InfraCalendarList$MonthItem,
};

function InfraCalendarList(props) {
  var setCurrDate = props.setCurrDate;
  var handleChangeMonthBy = props.handleChangeMonthBy;
  var __disableFutureDates = props.disableFutureDates;
  var __disablePastDates = props.disablePastDates;
  var __endDate = props.endDate;
  var __startDate = props.startDate;
  var startDate = __startDate !== undefined ? __startDate : "";
  var endDate = __endDate !== undefined ? __endDate : "";
  var disablePastDates =
    __disablePastDates !== undefined ? __disablePastDates : true;
  var disableFutureDates =
    __disableFutureDates !== undefined ? __disableFutureDates : false;
  var currDateTemp = new Date(props.currDateIm.valueOf());
  var tempDate = currDateTemp.setMonth(currDateTemp.getMonth() | 0);
  var tempMonth = new Date(tempDate).getMonth();
  var tempYear = new Date(tempDate).getFullYear();
  return React.createElement(
    "span",
    {
      className:
        "flex flex-1 flex-row overflow-auto border-t border-b dark:border-jp-gray-900 select-none",
    },
    React.createElement(
      "span",
      undefined,
      props.monthYearListVisibility
        ? React.createElement(
            "div",
            {
              className: "flex text-jp-gray-600 justify-between w-80",
            },
            React.createElement(
              "ul",
              {
                className: "w-1/2 h-80 overflow-scroll",
              },
              months.map(function (mon, i) {
                return JsxPPXReactSupportU.createElementWithKey(
                  i.toString(),
                  InfraCalendarList$MonthItem,
                  {
                    index: i,
                    tempMonth: tempMonth,
                    tempYear: tempYear,
                    handleChangeMonthBy: handleChangeMonthBy,
                    setCurrDate: setCurrDate,
                    mon: mon,
                  },
                );
              }),
            ),
            React.createElement(
              "ul",
              {
                className: "w-1/2",
              },
              years.map(function (year, i) {
                return JsxPPXReactSupportU.createElementWithKey(
                  i.toString(),
                  InfraCalendarList$YearItem,
                  {
                    tempYear: tempYear,
                    year: year,
                    handleChangeMonthBy: handleChangeMonthBy,
                    setCurrDate: setCurrDate,
                    tempMonth: tempMonth,
                  },
                );
              }),
            ),
          )
        : React.createElement(InfraCalendar.make, {
            month: getMonthFromFloat(tempMonth),
            year: tempYear | 0,
            onDateClick: props.onDateClick,
            showTitle: false,
            cellHighlighter: props.cellHighlighter,
            cellRenderer: props.cellRenderer,
            startDate: startDate,
            endDate: endDate,
            disablePastDates: disablePastDates,
            disableFutureDates: disableFutureDates,
          }),
    ),
  );
}

var make = InfraCalendarList;

export {
  startYear,
  years,
  months,
  getMonthInStr,
  getMonthFromFloat,
  YearItem,
  MonthItem,
  make,
};
/*  Not a pure module */
