// Generated by ReScript, PLEASE EDIT WITH CARE

import Dayjs from "dayjs";
import * as React from "react";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as LogicUtils from "../utils/LogicUtils.bs.js";
import * as Core__Array from "@rescript/core/src/Core__Array.bs.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as TimeZoneHook from "../hooks/TimeZoneHook.bs.js";
import * as JsxPPXReactSupportU from "rescript/lib/es6/jsxPPXReactSupportU.js";

function defaultCellHighlighter(param) {
  return {
    highlightSelf: false,
    highlightLeft: false,
    highlightRight: false,
  };
}

function defaultCellRenderer(obj) {
  if (obj === undefined) {
    return "";
  }
  var day = obj.split("-");
  return Core__Option.getOr(day[2], "");
}

function InfraCalendar$TableRow(props) {
  var __disableFutureDates = props.disableFutureDates;
  var __disablePastDates = props.disablePastDates;
  var __endDate = props.endDate;
  var __startDate = props.startDate;
  var __cellRenderer = props.cellRenderer;
  var __cellHighlighter = props.cellHighlighter;
  var onDateClick = props.onDateClick;
  var year = props.year;
  var month = props.month;
  var item = props.item;
  var cellHighlighter =
    __cellHighlighter !== undefined
      ? __cellHighlighter
      : defaultCellHighlighter;
  var cellRenderer =
    __cellRenderer !== undefined ? __cellRenderer : defaultCellRenderer;
  var startDate = __startDate !== undefined ? __startDate : "";
  var endDate = __endDate !== undefined ? __endDate : "";
  var disablePastDates =
    __disablePastDates !== undefined ? __disablePastDates : true;
  var disableFutureDates =
    __disableFutureDates !== undefined ? __disableFutureDates : false;
  var customTimezoneToISOString = TimeZoneHook.useCustomTimeZoneToIsoString();
  if (Caml_obj.equal(item, Core__Array.make(7, ""))) {
    return null;
  } else {
    return React.createElement(
      "tr",
      {
        className: "transition duration-300 ease-in-out",
      },
      item.map(function (obj, cellIndex) {
        var date = new Date(
          customTimezoneToISOString(
            String(year),
            String(month + 1.0),
            String(LogicUtils.isEmptyString(obj) ? "01" : obj),
            "00",
            "00",
            "00",
          ),
        );
        var dateToday = new Date();
        var todayInitial = dateToday.setHours(0.0, 0.0, 0.0, 0.0);
        var isFutureDate = todayInitial - date.getTime() < 0.0;
        var onClick = function (_evt) {
          var isClickDisabled = isFutureDate
            ? disableFutureDates
            : disablePastDates;
          if (
            !isClickDisabled &&
            onDateClick !== undefined &&
            LogicUtils.isNonEmptyString(obj)
          ) {
            return onDateClick(Dayjs(date.toISOString()).format("YYYY-MM-DD"));
          }
        };
        var hSelf = cellHighlighter(
          Dayjs(date.toString()).format("YYYY-MM-DD"),
        );
        var dayClass =
          (isFutureDate && disableFutureDates) ||
          (!isFutureDate && disablePastDates)
            ? "cursor-not-allowed"
            : "cursor-default";
        var classN =
          LogicUtils.isEmptyString(obj) || hSelf.highlightSelf
            ? "h-12 w-12 font-fira-code text-center dark:text-jp-gray-text_darktheme text-opacity-75 " +
              dayClass +
              " p-0 pb-1"
            : "cursor-pointer h-12 w-12 text-center font-fira-code font-medium dark:text-jp-gray-text_darktheme text-opacity-75 dark:hover:bg-opacity-100 " +
              dayClass +
              " p-0 pb-1";
        var c2 =
          LogicUtils.isNonEmptyString(obj) && hSelf.highlightSelf
            ? "h-full w-full cursor-pointer flex border flex-1 justify-center items-center bg-blue-500 bg-opacity-100 dark:bg-opacity-100 rounded-full"
            : "h-full w-full";
        var shouldHighlight = function (startDate, endDate, obj, month, year) {
          if (
            !(
              LogicUtils.isNonEmptyString(startDate) &&
              LogicUtils.isNonEmptyString(obj)
            )
          ) {
            return "h-full w-full";
          }
          var getDate = function (date) {
            return new Date(
              Number(Core__Option.getOr(date[0], "")),
              Number(String(Number(Core__Option.getOr(date[1], "")) - 1.0)),
              Number(Core__Option.getOr(date[2], "")),
            );
          };
          var parsedStartDate = getDate(startDate.split("-"));
          var z = getDate([year, month, obj]);
          if (!LogicUtils.isNonEmptyString(endDate)) {
            if (Caml_obj.equal(z, parsedStartDate)) {
              return "h-full w-full flex flex-1 justify-center items-center bg-blue-500 bg-opacity-100 dark:bg-blue-500 text-white dark:hover:text-jp-gray-text_darktheme dark:bg-opacity-100 rounded-full";
            } else {
              return "h-full w-full";
            }
          }
          var parsedEndDate = getDate(endDate.split("-"));
          if (
            Caml_obj.equal(z, parsedStartDate) &&
            Caml_obj.equal(z, parsedEndDate)
          ) {
            return "h-full w-full flex flex-1 justify-center items-center bg-blue-500 bg-opacity-100 dark:bg-blue-500 dark:bg-opacity-100 text-white dark:hover:text-jp-gray-text_darktheme rounded-full";
          } else if (Caml_obj.equal(z, parsedStartDate)) {
            return "h-full w-full flex flex-1 justify-center items-center bg-blue-500 bg-opacity-100 dark:bg-blue-500 dark:bg-opacity-100 text-white dark:hover:text-jp-gray-text_darktheme rounded-l-full ";
          } else if (Caml_obj.equal(z, parsedEndDate)) {
            return "h-full w-full flex flex-1 justify-center items-center bg-blue-500 bg-opacity-100 dark:bg-blue-500 dark:bg-opacity-100 text-white dark:hover:text-jp-gray-text_darktheme rounded-r-full ";
          } else if (
            Caml_obj.greaterthan(z, parsedStartDate) &&
            Caml_obj.lessthan(z, parsedEndDate)
          ) {
            return "h-full w-full flex flex-1 justify-center items-center bg-blue-500 bg-opacity-100 dark:bg-blue-500 text-white dark:hover:text-jp-gray-text_darktheme dark:bg-opacity-100";
          } else {
            return "h-full w-full";
          }
        };
        var c3 = shouldHighlight(
          startDate,
          endDate,
          obj,
          (month + 1.0).toString(),
          year.toString(),
        );
        return React.createElement(
          "td",
          {
            key: cellIndex.toString(),
            className: classN,
            onClick: onClick,
          },
          React.createElement(
            "span",
            {
              className:
                (LogicUtils.isEmptyString(startDate) ? c2 : c3) +
                " " +
                (LogicUtils.isNonEmptyString(obj)
                  ? "dark:hover:border-jp-gray-400 dark:text-jp-gray-text_darktheme dark:hover:text-white"
                  : ""),
            },
            React.createElement(
              "span",
              {
                className: LogicUtils.isEmptyString(obj)
                  ? ""
                  : "border border-transparent hover:text-jp-gray-950 hover:border-jp-gray-950 p-3 hover:bg-white dark:hover:bg-jp-gray-950 dark:hover:text-white rounded-full",
              },
              cellRenderer(
                LogicUtils.isEmptyString(obj)
                  ? undefined
                  : Dayjs(date.toString()).format("YYYY-MM-DD"),
              ),
            ),
          ),
        );
      }),
    );
  }
}

var TableRow = {
  defaultCellHighlighter: defaultCellHighlighter,
  defaultCellRenderer: defaultCellRenderer,
  make: InfraCalendar$TableRow,
};

function InfraCalendar(props) {
  var __disableFutureDates = props.disableFutureDates;
  var __disablePastDates = props.disablePastDates;
  var __endDate = props.endDate;
  var __startDate = props.startDate;
  var cellRenderer = props.cellRenderer;
  var cellHighlighter = props.cellHighlighter;
  var __showTitle = props.showTitle;
  var onDateClick = props.onDateClick;
  var year = props.year;
  var month = props.month;
  var showTitle = __showTitle !== undefined ? __showTitle : true;
  var startDate = __startDate !== undefined ? __startDate : "";
  var endDate = __endDate !== undefined ? __endDate : "";
  var disablePastDates =
    __disablePastDates !== undefined ? __disablePastDates : true;
  var disableFutureDates =
    __disableFutureDates !== undefined ? __disableFutureDates : false;
  var months = [
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
  ];
  var heading = ["S", "M", "T", "W", "T", "F", "S"];
  var getMonthInStr = function (mon) {
    switch (mon) {
      case "Jan":
        return "January, ";
      case "Feb":
        return "February, ";
      case "Mar":
        return "March, ";
      case "Apr":
        return "April, ";
      case "May":
        return "May, ";
      case "Jun":
        return "June, ";
      case "Jul":
        return "July, ";
      case "Aug":
        return "August, ";
      case "Sep":
        return "September, ";
      case "Oct":
        return "October, ";
      case "Nov":
        return "November, ";
      case "Dec":
        return "December, ";
    }
  };
  var firstDay = new Date(year, months.indexOf(month)).getDay();
  var daysInMonth;
  switch (month) {
    case "Feb":
      daysInMonth = LogicUtils.checkLeapYear(year) ? 29 : 28;
      break;
    case "Apr":
    case "Jun":
    case "Sep":
    case "Nov":
      daysInMonth = 30;
      break;
    default:
      daysInMonth = 31;
  }
  var dummyRow = Core__Array.make(6, Core__Array.make(7, ""));
  var rowMapper = function (row, indexRow) {
    return row.map(function (_item, index) {
      var subFactor = firstDay | 0;
      if (indexRow === 0 && index < (firstDay | 0)) {
        return "";
      } else if (indexRow === 0) {
        return (
          (((indexRow + ((index + 1) | 0)) | 0) - subFactor) |
          0
        ).toString();
      } else if (
        ((((Math.imul(indexRow, 7) + ((index + 1) | 0)) | 0) - subFactor) | 0) >
        daysInMonth
      ) {
        return "";
      } else {
        return (
          (((Math.imul(indexRow, 7) + ((index + 1) | 0)) | 0) - subFactor) |
          0
        ).toString();
      }
    });
  };
  var rowInfo = dummyRow.map(rowMapper);
  return React.createElement(
    "div",
    {
      className: "text-sm px-4 pb-2",
    },
    showTitle
      ? React.createElement(
          "h3",
          {
            className: "text-center font-bold text-lg text-gray-500 ",
          },
          getMonthInStr(month),
          React.createElement(
            "span",
            {
              className: "font-fira-code",
            },
            year.toString(),
          ),
        )
      : null,
    React.createElement(
      "table",
      {
        className: "table-auto min-w-full",
      },
      React.createElement(
        "thead",
        undefined,
        React.createElement(
          "tr",
          undefined,
          heading.map(function (item, i) {
            return React.createElement(
              "th",
              {
                key: i.toString(),
                className: "p-0",
              },
              React.createElement(
                "div",
                {
                  className:
                    "flex flex-1 justify-center py-2 font-medium text-jp-gray-700 dark:text-jp-gray-text_darktheme dark:text-opacity-50",
                },
                item,
              ),
            );
          }),
        ),
      ),
      React.createElement(
        "tbody",
        undefined,
        rowInfo.map(function (item, rowIndex) {
          return JsxPPXReactSupportU.createElementWithKey(
            rowIndex.toString(),
            InfraCalendar$TableRow,
            {
              item: item,
              month: months.indexOf(month),
              year: year,
              rowIndex: rowIndex,
              onDateClick: onDateClick,
              cellHighlighter: cellHighlighter,
              cellRenderer: cellRenderer,
              startDate: startDate,
              endDate: endDate,
              disablePastDates: disablePastDates,
              disableFutureDates: disableFutureDates,
            },
          );
        }),
      ),
    ),
  );
}

var make = InfraCalendar;

export { TableRow, make };
/* dayjs Not a pure module */
