// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "./Icon.bs.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ErrorBoundary from "./ErrorBoundary.bs.js";

function Loader(props) {
  var __loadingTextColor = props.loadingTextColor;
  var __customSpinnerIconColor = props.customSpinnerIconColor;
  var __slow = props.slow;
  var __children = props.children;
  var children =
    __children !== undefined ? Caml_option.valFromOption(__children) : null;
  var slow = __slow !== undefined ? __slow : false;
  var customSpinnerIconColor =
    __customSpinnerIconColor !== undefined ? __customSpinnerIconColor : "";
  var loadingTextColor =
    __loadingTextColor !== undefined ? __loadingTextColor : "";
  var animationType = slow ? "animate-spin-slow" : "animate-spin";
  var size = slow ? 60 : 20;
  var loader = React.createElement(
    "div",
    {
      className:
        "flex flex-col py-16 text-center items-center " + loadingTextColor,
    },
    React.createElement(
      "div",
      {
        className: animationType + " mb-10",
      },
      React.createElement(Icon.make, {
        name: "spinner",
        size: size,
        customIconColor: customSpinnerIconColor,
      }),
    ),
    children,
  );
  return React.createElement(
    "div",
    {
      className: "flex flex-col",
    },
    React.createElement(
      "div",
      {
        className: "w-full flex justify-center py-10",
      },
      React.createElement(
        "div",
        {
          className: "w-20 h-16",
        },
        React.createElement(React.Suspense, {
          children: Caml_option.some(
            React.createElement(ErrorBoundary.make, {
              children: loader,
            }),
          ),
          fallback: Caml_option.some(loader),
        }),
      ),
    ),
  );
}

var make = Loader;

export { make };
/* Icon Not a pure module */
