// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Form from "../utils/Form.bs.js";
import * as React from "react";
import * as SelectBox from "./SelectBox.bs.js";
import * as Core__JSON from "@rescript/core/src/Core__JSON.bs.js";
import * as EntityType from "../entities/EntityType.bs.js";
import * as MatchMedia from "../context/MatchMedia.bs.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as FormRenderer from "./form/FormRenderer.bs.js";
import * as ReactFinalForm from "../libraries/ReactFinalForm.bs.js";
import * as JsonFlattenUtils from "../utils/JsonFlattenUtils.bs.js";
import * as ReactFinalForm$1 from "react-final-form";
import * as RemoteFiltersUtils from "./RemoteFiltersUtils.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as CustomInputSelectBox from "./CustomInputSelectBox.bs.js";

function LocalFilters$CheckLocalFilters(props) {
  var applyFilters = props.applyFilters;
  var addFilters = props.addFilters;
  var removeFilters = props.removeFilters;
  var checkedFilters = props.checkedFilters;
  var options = props.options;
  var isMobileView = MatchMedia.useMobileChecker();
  var formState = ReactFinalForm$1.useFormState(
    ReactFinalForm.useFormSubscription(["values"]),
  );
  var values = formState.values;
  React.useEffect(
    function () {
      if (formState.dirty) {
        var valuesDict = Core__JSON.Decode.object(formState.values);
        if (valuesDict !== undefined) {
          applyFilters(valuesDict);
        }
      }
    },
    [values],
  );
  var onChangeSelect = function (ev) {
    var newlyAdded = ev.filter(function (newVal) {
      return !checkedFilters.includes(newVal);
    });
    if (newlyAdded.length > 0) {
      return addFilters(newlyAdded);
    } else {
      return removeFilters(ev, values);
    }
  };
  var fieldWrapperClass = isMobileView ? "" : "px-1 flex flex-col";
  var selectOptions = options.map(function (obj) {
    return obj.urlKey;
  });
  return React.createElement(
    "div",
    {
      className: "flex flex-row flex-wrap ",
    },
    React.createElement(FormRenderer.FieldsRenderer.make, {
      fields: props.selectedFiltersList,
      fieldWrapperClass: fieldWrapperClass,
      labelClass: "",
      labelPadding: "",
    }),
    React.createElement(
      "div",
      {
        className:
          "md:justify-between flex flex-row items-center flex-wrap " +
          props.addFilterStyle,
      },
      options.length > 0
        ? React.createElement(
            "div",
            {
              className: "flex",
            },
            React.createElement(CustomInputSelectBox.make, {
              onChange: onChangeSelect,
              value: checkedFilters.map(function (prim) {
                return prim;
              }),
              buttonText: "Add Filters",
              options: SelectBox.makeOptions(selectOptions),
              allowMultiSelect: true,
              isDropDown: true,
              hideMultiSelectButtons: true,
              buttonType: "FilterAdd",
              searchable: props.showSelectFiltersSearch,
            }),
          )
        : null,
    ),
  );
}

var CheckLocalFilters = {
  make: LocalFilters$CheckLocalFilters,
};

function LocalFilters(props) {
  var __disableURIdecode = props.disableURIdecode;
  var __showSelectFiltersSearch = props.showSelectFiltersSearch;
  var __customLocalFilterStyle = props.customLocalFilterStyle;
  var __addFilterStyle = props.addFilterStyle;
  var tableName = props.tableName;
  var __localSearchFilters = props.localSearchFilters;
  var setLocalSearchFilters = props.setLocalSearchFilters;
  var __ignoreUrlUpdate = props.ignoreUrlUpdate;
  var __path = props.path;
  var __mandatoryRemoteKeys = props.mandatoryRemoteKeys;
  var localOptions = props.localOptions;
  var localFilters = props.localFilters;
  var setOffset = props.setOffset;
  var mandatoryRemoteKeys =
    __mandatoryRemoteKeys !== undefined ? __mandatoryRemoteKeys : [];
  var path = __path !== undefined ? __path : "";
  var ignoreUrlUpdate =
    __ignoreUrlUpdate !== undefined ? __ignoreUrlUpdate : false;
  var localSearchFilters =
    __localSearchFilters !== undefined ? __localSearchFilters : "";
  var addFilterStyle = __addFilterStyle !== undefined ? __addFilterStyle : "";
  var customLocalFilterStyle =
    __customLocalFilterStyle !== undefined ? __customLocalFilterStyle : "";
  var showSelectFiltersSearch =
    __showSelectFiltersSearch !== undefined ? __showSelectFiltersSearch : false;
  var disableURIdecode =
    __disableURIdecode !== undefined ? __disableURIdecode : false;
  var defaultFilters = props.entity.defaultFilters;
  var match = React.useState(function () {
    return localFilters.map(function (item) {
      return item.field;
    });
  });
  var setSelectedFiltersList = match[1];
  var selectedFiltersList = match[0];
  var match$1 = React.useState(function () {
    return [];
  });
  var setCheckedFilters = match$1[1];
  var checkedFilters = match$1[0];
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var searchParams = disableURIdecode ? url.search : decodeURI(url.search);
  var match$2 = React.useState(function () {
    return {};
  });
  var setInitialValueJson = match$2[1];
  var initialValueJson = match$2[0];
  var remoteFiltersJson = RemoteFiltersUtils.getInitialValuesFromUrl(
    searchParams,
    props.remoteFilters,
    props.remoteOptions,
    mandatoryRemoteKeys,
    undefined,
  );
  var remoteFilterDict = JsonFlattenUtils.flattenObject(
    remoteFiltersJson,
    false,
  );
  React.useEffect(
    function () {
      var searchValues = ignoreUrlUpdate ? localSearchFilters : searchParams;
      var initialValues = RemoteFiltersUtils.getInitialValuesFromUrl(
        searchValues,
        localFilters,
        localOptions,
        undefined,
        undefined,
      );
      var localCheckedFilters = checkedFilters.slice();
      var localSelectedFiltersList = selectedFiltersList.slice();
      Object.entries(
        Core__Option.getOr(Core__JSON.Decode.object(initialValues), {}),
      ).forEach(function (entry) {
        var key = entry[0];
        var includes = checkedFilters.includes(key);
        if (includes) {
          return;
        }
        var optionalOption = localOptions.find(function (option) {
          return option.urlKey === key;
        });
        if (optionalOption !== undefined) {
          localSelectedFiltersList.push(optionalOption.field);
          localCheckedFilters.push(key);
          return;
        }
      });
      setCheckedFilters(function (_prev) {
        return localCheckedFilters;
      });
      setSelectedFiltersList(function (_prev) {
        return localSelectedFiltersList;
      });
      setInitialValueJson(function (param) {
        return initialValues;
      });
    },
    [searchParams, localSearchFilters],
  );
  var applyFilters = function (valuesDict) {
    RemoteFiltersUtils.applyFilters(
      valuesDict,
      defaultFilters,
      setOffset,
      path,
      remoteFilterDict,
      localOptions,
      ignoreUrlUpdate,
      setLocalSearchFilters,
      tableName,
      undefined,
      undefined,
    );
  };
  var addFilters = function (newlyAdded) {
    var localCheckedFilters = checkedFilters.slice();
    var localSelectedFiltersList = selectedFiltersList.slice();
    newlyAdded.forEach(function (value) {
      var optionObjArry = localOptions.filter(function (option) {
        return option.urlKey === value;
      });
      var defaultEntityOptionType = EntityType.getDefaultEntityOptionType();
      var optionObj = Core__Option.getOr(
        optionObjArry[0],
        defaultEntityOptionType,
      );
      localSelectedFiltersList.push(optionObj.field);
      localCheckedFilters.push(value);
    });
    setCheckedFilters(function (_prev) {
      return localCheckedFilters;
    });
    setSelectedFiltersList(function (_prev) {
      return localSelectedFiltersList;
    });
  };
  var removeFilters = function (fieldNameArr, values) {
    var toBeRemoved = checkedFilters.filter(function (oldVal) {
      return !fieldNameArr.includes(oldVal);
    });
    var finalFieldList = selectedFiltersList.filter(function (val) {
      return Core__Option.getOr(
        Core__Option.map(val.inputNames[0], function (name) {
          return !toBeRemoved.includes(name);
        }),
        false,
      );
    });
    var filtersAfterRemoving = checkedFilters.filter(function (val) {
      return !toBeRemoved.includes(val);
    });
    var newInitialValues = Object.fromEntries(
      Object.entries(
        Core__Option.getOr(Core__JSON.Decode.object(initialValueJson), {}),
      ).filter(function (entry) {
        return !toBeRemoved.includes(entry[0]);
      }),
    );
    var dict = Core__JSON.Decode.object(values);
    if (dict !== undefined) {
      Object.entries(dict).forEach(function (entry) {
        var key = entry[0];
        if (toBeRemoved.includes(key)) {
          dict[key] = "";
        }
        applyFilters(dict);
      });
    }
    setInitialValueJson(function (param) {
      return newInitialValues;
    });
    setCheckedFilters(function (_prev) {
      return filtersAfterRemoving;
    });
    setSelectedFiltersList(function (_prev) {
      return finalFieldList;
    });
  };
  return React.createElement(
    "div",
    {
      className: "bg-transparent flex flex-row " + customLocalFilterStyle,
    },
    React.createElement(
      "div",
      undefined,
      React.createElement(Form.make, {
        children: React.createElement(LocalFilters$CheckLocalFilters, {
          options: localOptions,
          checkedFilters: checkedFilters,
          removeFilters: removeFilters,
          addFilters: addFilters,
          applyFilters: applyFilters,
          selectedFiltersList: selectedFiltersList,
          addFilterStyle: addFilterStyle,
          showSelectFiltersSearch: showSelectFiltersSearch,
        }),
        initialValues: initialValueJson,
      }),
    ),
  );
}

var makeFieldInfo = FormRenderer.makeFieldInfo;

var make = LocalFilters;

export { makeFieldInfo, CheckLocalFilters, make };
/* Form Not a pure module */
