// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "./Icon.bs.js";
import * as React from "react";
import * as Button from "./Button.bs.js";
import * as ButtonGroup from "./ButtonGroup.bs.js";
import * as JsxPPXReactSupportU from "rescript/lib/es6/jsxPPXReactSupportU.js";

function NewPagination(props) {
  var __btnCount = props.btnCount;
  var paginate = props.paginate;
  var currentPage = props.currentPage;
  var btnCount = __btnCount !== undefined ? __btnCount : 4;
  var pageNumbers = [];
  var total = Math.ceil(props.totalResults / props.resultsPerPage) | 0;
  for (var x = 1; x <= total; ++x) {
    pageNumbers.push(x);
  }
  var pageToLeft =
    ((btnCount - ((total - currentPage) | 0)) | 0) < ((btnCount / 2) | 0)
      ? (btnCount / 2) | 0
      : (btnCount - ((total - currentPage) | 0)) | 0;
  var startIndex = Math.max(1, (currentPage - pageToLeft) | 0);
  var endIndex = Math.min((startIndex + btnCount) | 0, total);
  var nonEmpty = function (s) {
    if (s >= startIndex) {
      return s <= endIndex;
    } else {
      return false;
    }
  };
  return React.createElement(
    ButtonGroup.make,
    {
      children: null,
    },
    currentPage > 1
      ? React.createElement(Icon.make, {
          name: "chevron-left",
          size: 16,
          className: "fill-ardra-secondary-300",
          onClick: function (_evt) {
            paginate(Math.max(1, (currentPage - 1) | 0));
          },
        })
      : React.createElement(Icon.make, {
          name: "leftDisabledPaginator",
          size: 16,
          onClick: function (_evt) {
            paginate(Math.max(1, (currentPage - 1) | 0));
          },
        }),
    pageNumbers.filter(nonEmpty).map(function (number, idx) {
      return React.createElement(
        "div",
        {
          className: "p-2",
        },
        JsxPPXReactSupportU.createElementWithKey(idx.toString(), Button.make, {
          text: number.toString(),
          buttonType: "Pill",
          onClick: function (_evt) {
            paginate(number);
          },
          textStyle: "text-[#0E111E] text-[14px]",
          textWeight: "font-light",
          customButtonStyle: "rounded-[4px] w-[39px] h-[36px]",
        }),
      );
    }),
    currentPage < pageNumbers.length
      ? React.createElement(Icon.make, {
          name: "chevron-right",
          size: 16,
          onClick: function (_evt) {
            paginate((currentPage + 1) | 0);
          },
        })
      : React.createElement(Icon.make, {
          name: "rightDisabledPaginator",
          size: 16,
          onClick: function (_evt) {
            paginate((currentPage + 1) | 0);
          },
        }),
  );
}

var make = NewPagination;

export { make };
/* Icon Not a pure module */
