// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as UnauthorizedPage from "../components/UnauthorizedPage.bs.js";

function AccessControl(props) {
  var __isEnabled = props.isEnabled;
  var isEnabled = __isEnabled !== undefined ? __isEnabled : true;
  var isAccessAllowed = props.permission === "Access";
  if (isEnabled && isAccessAllowed) {
    return props.children;
  } else {
    return React.createElement(UnauthorizedPage.make, {});
  }
}

var make = AccessControl;

export { make };
/* react Not a pure module */
