// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../components/Icon.bs.js";
import * as Link from "../components/router/Link.bs.js";
import * as React from "react";
import * as RenderIf from "./RenderIf.bs.js";
import * as GlobalVars from "./GlobalVars.bs.js";
import * as LogicUtils from "./LogicUtils.bs.js";
import * as PopUpState from "../hooks/PopUpState.bs.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as ThemeProvider from "../context/ThemeProvider.bs.js";
import * as AddDataAttributes from "../components/AddDataAttributes.bs.js";
import * as JsxPPXReactSupportU from "rescript/lib/es6/jsxPPXReactSupportU.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

var arrowDivider = React.createElement(
  "span",
  {
    className: "ml-2 mr-2",
  },
  React.createElement(Icon.make, {
    name: "chevron-right",
    size: 8,
    className: "align-middle  text-jp-gray-930",
  }),
);

function BreadCrumbNavigation(props) {
  var __linkTextClass = props.linkTextClass;
  var __commonTextClass = props.commonTextClass;
  var __cursorStyle = props.cursorStyle;
  var __is_reverse = props.is_reverse;
  var __currentPageTitle = props.currentPageTitle;
  var __path = props.path;
  var path = __path !== undefined ? __path : [];
  var currentPageTitle =
    __currentPageTitle !== undefined ? __currentPageTitle : "";
  var is_reverse = __is_reverse !== undefined ? __is_reverse : false;
  var cursorStyle = __cursorStyle !== undefined ? __cursorStyle : "cursor-help";
  var commonTextClass =
    __commonTextClass !== undefined ? __commonTextClass : "";
  var linkTextClass = __linkTextClass !== undefined ? __linkTextClass : "";
  var match = React.useContext(ThemeProvider.themeContext);
  var prefix = LogicUtils.useUrlPrefix();
  var showPopUp = PopUpState.useShowPopUp();
  var pathLength = path.length;
  var textClass = match.globalUIConfig.font.textColor.primaryNormal;
  var flexDirection = is_reverse
    ? "flex-wrap flex-row-reverse"
    : "flex-wrap flex-row";
  return React.createElement(
    "div",
    {
      className:
        "flex " + flexDirection + " font-semibold gap-2  items-center w-fit",
    },
    path.map(function (crumb, index) {
      var showCrumb = index <= 2 || index === ((pathLength - 1) | 0);
      var collapse = index === 2 && pathLength > 3;
      var fn = crumb.onClick;
      var onClick =
        fn !== undefined
          ? fn
          : function (_ev) {
              showPopUp({
                heading: "Heads up!",
                description: Core__Option.getOr(crumb.warning, ""),
                popUpType: ["Warning", "WithIcon"],
                handleCancel: {
                  text: "No, don't go back",
                },
                handleConfirm: {
                  text: "Yes, go back",
                  onClick: function (param) {
                    RescriptReactRouter.push(
                      GlobalVars.appendDashboardPath(crumb.link),
                    );
                  },
                },
              });
            };
      var tmp;
      if (collapse) {
        tmp = React.createElement(
          "div",
          {
            className:
              "flex flex-row gap-1 text-jp-2-gray-100 font-medium items-center justify-center",
          },
          React.createElement("span", undefined, "..."),
          React.createElement(Icon.make, {
            name: "angle-down",
            size: 12,
          }),
        );
      } else {
        var match = crumb.warning;
        var match$1 = crumb.onClick;
        var tmp$1;
        var exit = 0;
        if (match !== undefined || match$1 !== undefined) {
          exit = 1;
        } else {
          tmp$1 = React.createElement(Link.make, {
            to_: prefix + crumb.link,
            children: crumb.title,
            className: textClass + " " + linkTextClass + " " + commonTextClass,
          });
        }
        if (exit === 1) {
          tmp$1 = React.createElement(
            "a",
            {
              className:
                textClass +
                " " +
                cursorStyle +
                " " +
                linkTextClass +
                " " +
                commonTextClass,
              onClick: onClick,
            },
            crumb.title,
          );
        }
        tmp = React.createElement(AddDataAttributes.make, {
          attributes: [["data-breadcrumb", crumb.title]],
          children: React.createElement("div", undefined, tmp$1),
        });
      }
      return JsxPPXReactSupportU.createElementWithKey(
        index.toString(),
        RenderIf.make,
        {
          condition: showCrumb,
          children: React.createElement(
            "div",
            {
              className: "flex " + flexDirection + "  items-center",
            },
            tmp,
            arrowDivider,
          ),
        },
      );
    }),
    React.createElement(AddDataAttributes.make, {
      attributes: [["data-breadcrumb", currentPageTitle]],
      children: React.createElement(
        "div",
        {
          className: "text-fs-14 text-jp-gray-930 " + commonTextClass,
        },
        currentPageTitle,
      ),
    }),
  );
}

var make = BreadCrumbNavigation;

export { arrowDivider, make };
/* arrowDivider Not a pure module */
