// Generated by ReScript, PLEASE EDIT WITH CARE

var currencyList = [
  "AED",
  "ALL",
  "AMD",
  "ANG",
  "ARS",
  "AUD",
  "AWG",
  "AZN",
  "BBD",
  "BDT",
  "BHD",
  "BMD",
  "BND",
  "BOB",
  "BRL",
  "BSD",
  "BWP",
  "BZD",
  "CAD",
  "CHF",
  "COP",
  "CRC",
  "CUP",
  "CZK",
  "DKK",
  "DOP",
  "DZD",
  "EGP",
  "ETB",
  "EUR",
  "FJD",
  "GBP",
  "GHS",
  "GIP",
  "GMD",
  "GTQ",
  "GYD",
  "HKD",
  "HNL",
  "HTG",
  "HUF",
  "IDR",
  "ILS",
  "INR",
  "JMD",
  "JOD",
  "JPY",
  "KES",
  "KGS",
  "KHR",
  "KRW",
  "KWD",
  "KYD",
  "KZT",
  "LAK",
  "LBP",
  "LKR",
  "LRD",
  "LSL",
  "MAD",
  "MDL",
  "MKD",
  "MMK",
  "MNT",
  "MOP",
  "MUR",
  "MVR",
  "MWK",
  "MXN",
  "MYR",
  "NAD",
  "NGN",
  "NIO",
  "NOK",
  "NPR",
  "NZD",
  "OMR",
  "PEN",
  "PGK",
  "PHP",
  "PKR",
  "PLN",
  "QAR",
  "RON",
  "CNY",
  "RUB",
  "SAR",
  "SCR",
  "SEK",
  "SGD",
  "SLL",
  "SOS",
  "SSP",
  "SVC",
  "SZL",
  "THB",
  "TRY",
  "TTD",
  "TWD",
  "TZS",
  "USD",
];

function getCurrencyCodeStringFromVariant(currencyCode) {
  switch (currencyCode) {
    case "AED":
      return "AED";
    case "ALL":
      return "ALL";
    case "AMD":
      return "AMD";
    case "ANG":
      return "ANG";
    case "ARS":
      return "ARS";
    case "AUD":
      return "AUD";
    case "AWG":
      return "AWG";
    case "AZN":
      return "AZN";
    case "BBD":
      return "BBD";
    case "BDT":
      return "BDT";
    case "BHD":
      return "BHD";
    case "BMD":
      return "BMD";
    case "BND":
      return "BND";
    case "BOB":
      return "BOB";
    case "BRL":
      return "BRL";
    case "BSD":
      return "BSD";
    case "BWP":
      return "BWP";
    case "BZD":
      return "BZD";
    case "CAD":
      return "CAD";
    case "CHF":
      return "CHF";
    case "COP":
      return "COP";
    case "CRC":
      return "CRC";
    case "CUP":
      return "CUP";
    case "CZK":
      return "CZK";
    case "DKK":
      return "DKK";
    case "DOP":
      return "DOP";
    case "DZD":
      return "DZD";
    case "EGP":
      return "EGP";
    case "ETB":
      return "ETB";
    case "EUR":
      return "EUR";
    case "FJD":
      return "FJD";
    case "GBP":
      return "GBP";
    case "GHS":
      return "GHS";
    case "GIP":
      return "GIP";
    case "GMD":
      return "GMD";
    case "GTQ":
      return "GTQ";
    case "GYD":
      return "GYD";
    case "HKD":
      return "HKD";
    case "HNL":
      return "HNL";
    case "HTG":
      return "HTG";
    case "HUF":
      return "HUF";
    case "IDR":
      return "IDR";
    case "ILS":
      return "ILS";
    case "INR":
      return "INR";
    case "JMD":
      return "JMD";
    case "JOD":
      return "JOD";
    case "JPY":
      return "JPY";
    case "KES":
      return "KES";
    case "KGS":
      return "KGS";
    case "KHR":
      return "KHR";
    case "KRW":
      return "KRW";
    case "KWD":
      return "KWD";
    case "KYD":
      return "KYD";
    case "KZT":
      return "KZT";
    case "LAK":
      return "LAK";
    case "LBP":
      return "LBP";
    case "LKR":
      return "LKR";
    case "LRD":
      return "LRD";
    case "LSL":
      return "LSL";
    case "MAD":
      return "MAD";
    case "MDL":
      return "MDL";
    case "MKD":
      return "MKD";
    case "MMK":
      return "MMK";
    case "MNT":
      return "MNT";
    case "MOP":
      return "MOP";
    case "MUR":
      return "MUR";
    case "MVR":
      return "MVR";
    case "MWK":
      return "MWK";
    case "MXN":
      return "MXN";
    case "MYR":
      return "MYR";
    case "NAD":
      return "NAD";
    case "NGN":
      return "NGN";
    case "NIO":
      return "NIO";
    case "NOK":
      return "NOK";
    case "NPR":
      return "NPR";
    case "NZD":
      return "NZD";
    case "OMR":
      return "OMR";
    case "PEN":
      return "PEN";
    case "PGK":
      return "PGK";
    case "PHP":
      return "PHP";
    case "PKR":
      return "PKR";
    case "PLN":
      return "PLN";
    case "QAR":
      return "QAR";
    case "RON":
      return "RON";
    case "CNY":
      return "CNY";
    case "RUB":
      return "RUB";
    case "SAR":
      return "SAR";
    case "SCR":
      return "SCR";
    case "SEK":
      return "SEK";
    case "SGD":
      return "SGD";
    case "SLL":
      return "SLL";
    case "SOS":
      return "SOS";
    case "SSP":
      return "SSP";
    case "SVC":
      return "SVC";
    case "SZL":
      return "SZL";
    case "THB":
      return "THB";
    case "TRY":
      return "TRY";
    case "TTD":
      return "TTD";
    case "TWD":
      return "TWD";
    case "TZS":
      return "TZS";
    case "USD":
      return "USD";
  }
}

function getCurrencyCodeFromString(currencyCode) {
  switch (currencyCode) {
    case "AED":
      return "AED";
    case "ALL":
      return "ALL";
    case "AMD":
      return "AMD";
    case "ANG":
      return "ANG";
    case "ARS":
      return "ARS";
    case "AUD":
      return "AUD";
    case "AWG":
      return "AWG";
    case "AZN":
      return "AZN";
    case "BBD":
      return "BBD";
    case "BDT":
      return "BDT";
    case "BHD":
      return "BHD";
    case "BMD":
      return "BMD";
    case "BND":
      return "BND";
    case "BOB":
      return "BOB";
    case "BRL":
      return "BRL";
    case "BSD":
      return "BSD";
    case "BWP":
      return "BWP";
    case "BZD":
      return "BZD";
    case "CAD":
      return "CAD";
    case "CHF":
      return "CHF";
    case "CNY":
      return "CNY";
    case "COP":
      return "COP";
    case "CRC":
      return "CRC";
    case "CUP":
      return "CUP";
    case "CZK":
      return "CZK";
    case "DKK":
      return "DKK";
    case "DOP":
      return "DOP";
    case "DZD":
      return "DZD";
    case "EGP":
      return "EGP";
    case "ETB":
      return "ETB";
    case "EUR":
      return "EUR";
    case "FJD":
      return "FJD";
    case "GBP":
      return "GBP";
    case "GHS":
      return "GHS";
    case "GIP":
      return "GIP";
    case "GMD":
      return "GMD";
    case "GTQ":
      return "GTQ";
    case "GYD":
      return "GYD";
    case "HKD":
      return "HKD";
    case "HNL":
      return "HNL";
    case "HTG":
      return "HTG";
    case "HUF":
      return "HUF";
    case "IDR":
      return "IDR";
    case "ILS":
      return "ILS";
    case "INR":
      return "INR";
    case "JMD":
      return "JMD";
    case "JOD":
      return "JOD";
    case "JPY":
      return "JPY";
    case "KES":
      return "KES";
    case "KGS":
      return "KGS";
    case "KHR":
      return "KHR";
    case "KRW":
      return "KRW";
    case "KWD":
      return "KWD";
    case "KYD":
      return "KYD";
    case "KZT":
      return "KZT";
    case "LAK":
      return "LAK";
    case "LBP":
      return "LBP";
    case "LKR":
      return "LKR";
    case "LRD":
      return "LRD";
    case "LSL":
      return "LSL";
    case "MAD":
      return "MAD";
    case "MDL":
      return "MDL";
    case "MKD":
      return "MKD";
    case "MMK":
      return "MMK";
    case "MNT":
      return "MNT";
    case "MOP":
      return "MOP";
    case "MUR":
      return "MUR";
    case "MVR":
      return "MVR";
    case "MWK":
      return "MWK";
    case "MXN":
      return "MXN";
    case "MYR":
      return "MYR";
    case "NAD":
      return "NAD";
    case "NGN":
      return "NGN";
    case "NIO":
      return "NIO";
    case "NOK":
      return "NOK";
    case "NPR":
      return "NPR";
    case "NZD":
      return "NZD";
    case "OMR":
      return "OMR";
    case "PEN":
      return "PEN";
    case "PGK":
      return "PGK";
    case "PHP":
      return "PHP";
    case "PKR":
      return "PKR";
    case "PLN":
      return "PLN";
    case "QAR":
      return "QAR";
    case "RON":
      return "RON";
    case "RUB":
      return "RUB";
    case "SAR":
      return "SAR";
    case "SCR":
      return "SCR";
    case "SEK":
      return "SEK";
    case "SGD":
      return "SGD";
    case "SLL":
      return "SLL";
    case "SOS":
      return "SOS";
    case "SSP":
      return "SSP";
    case "SVC":
      return "SVC";
    case "SZL":
      return "SZL";
    case "THB":
      return "THB";
    case "TRY":
      return "TRY";
    case "TTD":
      return "TTD";
    case "TWD":
      return "TWD";
    case "TZS":
      return "TZS";
    default:
      return "USD";
  }
}

function getCurrencyNameFromCode(currencyCode) {
  switch (currencyCode) {
    case "AED":
      return "United Arab Emirates dirham";
    case "ALL":
      return "Albanian lek";
    case "AMD":
      return "Armenian dram";
    case "ANG":
      return "Netherlands Antillean guilder";
    case "ARS":
      return "Argentine peso";
    case "AUD":
      return "Australian dollar";
    case "AWG":
      return "Aruban florin";
    case "AZN":
      return "Azerbaijani manat";
    case "BBD":
      return "Barbados dollar";
    case "BDT":
      return "Bangladeshi taka";
    case "BHD":
      return "Bahraini dinar";
    case "BMD":
      return "Bermudian dollar";
    case "BND":
      return "Brunei dollar";
    case "BOB":
      return "Boliviano";
    case "BRL":
      return "Brazilian real";
    case "BSD":
      return "Bahamian dollar";
    case "BWP":
      return "Botswana pula";
    case "BZD":
      return "Belize dollar";
    case "CAD":
      return "Canadian dollar";
    case "CHF":
      return "Swiss franc";
    case "COP":
      return "Colombian peso";
    case "CRC":
      return "Costa Rican colon";
    case "CUP":
      return "Cuban peso";
    case "CZK":
      return "Czech koruna";
    case "DKK":
      return "Danish krone";
    case "DOP":
      return "Dominican peso";
    case "DZD":
      return "Algerian dinar";
    case "EGP":
      return "Egyptian pound";
    case "ETB":
      return "Ethiopian birr";
    case "EUR":
      return "Euro";
    case "FJD":
      return "Fiji dollar";
    case "GBP":
      return "Pound sterling";
    case "GHS":
      return "Ghanaian cedi";
    case "GIP":
      return "Gibraltar pound";
    case "GMD":
      return "Gambian dalasi";
    case "GTQ":
      return "Guatemalan quetzal";
    case "GYD":
      return "Guyanese dollar";
    case "HKD":
      return "Hong Kong dollar";
    case "HNL":
      return "Honduran lempira";
    case "HTG":
      return "Haitian gourde";
    case "HUF":
      return "Hungarian forint";
    case "IDR":
      return "Indonesian rupiah";
    case "ILS":
      return "Israeli new shekel";
    case "INR":
      return "Indian rupee";
    case "JMD":
      return "Jamaican dollar";
    case "JOD":
      return "Jordanian dinar";
    case "JPY":
      return "Japanese yen";
    case "KES":
      return "Kenyan shilling";
    case "KGS":
      return "Kyrgyzstani som";
    case "KHR":
      return "Cambodian riel";
    case "KRW":
      return "South Korean won";
    case "KWD":
      return "Kuwaiti dinar";
    case "KYD":
      return "Cayman Islands dollar";
    case "KZT":
      return "Kazakhstani tenge";
    case "LAK":
      return "Lao kip";
    case "LBP":
      return "Lebanese pound";
    case "LKR":
      return "Sri Lankan rupee";
    case "LRD":
      return "Liberian dollar";
    case "LSL":
      return "Lesotho loti";
    case "MAD":
      return "Moroccan dirham";
    case "MDL":
      return "Moldovan leu";
    case "MKD":
      return "Macedonian denar";
    case "MMK":
      return "Myanmar kyat";
    case "MNT":
      return "Mongolian tögrög";
    case "MOP":
      return "Macanese pataca";
    case "MUR":
      return "Mauritian rupee";
    case "MVR":
      return "Maldivian rufiyaa";
    case "MWK":
      return "Malawian kwacha";
    case "MXN":
      return "Mexican peso";
    case "MYR":
      return "Malaysian ringgit";
    case "NAD":
      return "Namibian dollar";
    case "NGN":
      return "Nigerian naira";
    case "NIO":
      return "Nicaraguan córdoba";
    case "NOK":
      return "Norwegian krone";
    case "NPR":
      return "Nepalese rupee";
    case "NZD":
      return "New Zealand dollar";
    case "OMR":
      return "Omani rial";
    case "PEN":
      return "Peruvian sol";
    case "PGK":
      return "Papua New Guinean kina";
    case "PHP":
      return "Philippine peso";
    case "PKR":
      return "Pakistani rupee";
    case "PLN":
      return "Polish złoty";
    case "QAR":
      return "Qatari riyal";
    case "RON":
      return "Romanian leu";
    case "CNY":
      return "Renminbi";
    case "RUB":
      return "Russian ruble";
    case "SAR":
      return "Saudi riyal";
    case "SCR":
      return "Seychelles rupee";
    case "SEK":
      return "Swedish krona";
    case "SGD":
      return "Singapore dollar";
    case "SLL":
      return "Sierra Leonean leone";
    case "SOS":
      return "Somali shilling";
    case "SSP":
      return "South Sudanese pound";
    case "SVC":
      return "Salvadoran colón";
    case "SZL":
      return "Swazi lilangeni";
    case "THB":
      return "Thai baht";
    case "TRY":
      return "Turkish lira";
    case "TTD":
      return "Trinidad and Tobago dollar";
    case "TWD":
      return "New Taiwan dollar";
    case "TZS":
      return "Tanzanian shilling";
    case "USD":
      return "United States dollar";
  }
}

function getCountryListFromCurrency(currencyCode) {
  switch (currencyCode) {
    case "AED":
      return ["AE"];
    case "ALL":
      return ["AL"];
    case "AMD":
      return ["AM"];
    case "ANG":
      return ["CW", "SX"];
    case "ARS":
      return ["AR"];
    case "AUD":
      return ["AU", "CX", "CC"];
    case "AWG":
      return ["AW"];
    case "AZN":
      return ["AZ"];
    case "BBD":
      return ["BB"];
    case "BDT":
      return ["BD"];
    case "BHD":
      return ["BH"];
    case "BMD":
      return ["BM"];
    case "BND":
      return ["BN"];
    case "BOB":
      return ["BO"];
    case "BRL":
      return ["BR"];
    case "BSD":
      return ["BS"];
    case "BWP":
      return ["BW"];
    case "BZD":
      return ["BZ"];
    case "CAD":
      return ["CA"];
    case "CHF":
      return ["LI", "CH"];
    case "COP":
      return ["CO"];
    case "CRC":
      return ["CR"];
    case "CUP":
      return ["CU"];
    case "CZK":
      return ["CZ"];
    case "DKK":
      return ["DK", "FO", "GL"];
    case "DOP":
      return ["DO"];
    case "DZD":
      return ["DZ"];
    case "EGP":
      return ["EG"];
    case "ETB":
      return ["ET"];
    case "EUR":
      return [
        "AD",
        "AT",
        "AX",
        "BE",
        "CY",
        "EE",
        "FI",
        "FR",
        "DE",
        "GR",
        "GP",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MT",
        "MQ",
        "YT",
        "MC",
        "ME",
        "NL",
        "PT",
        "RE",
        "BL",
        "MF",
        "PM",
        "SM",
        "SK",
        "SI",
        "ES",
        "VA",
        "GF",
        "TF",
        "MF",
      ];
    case "FJD":
      return ["FJ"];
    case "GBP":
      return ["GB", "GG", "IM", "JE"];
    case "GHS":
      return ["GH"];
    case "GIP":
      return ["GI"];
    case "GMD":
      return ["GM"];
    case "GTQ":
      return ["GT"];
    case "GYD":
      return ["GY"];
    case "HKD":
      return ["HK"];
    case "HNL":
      return ["HN"];
    case "HTG":
      return ["HT"];
    case "HUF":
      return ["HU"];
    case "IDR":
      return ["ID"];
    case "ILS":
      return ["IL", "PS"];
    case "INR":
      return ["IN"];
    case "JMD":
      return ["JM"];
    case "JOD":
      return ["JO"];
    case "JPY":
      return ["JP"];
    case "KES":
      return ["KE"];
    case "KGS":
      return ["KG"];
    case "KHR":
      return ["KH"];
    case "KRW":
      return ["KP", "KR"];
    case "KWD":
      return ["KW"];
    case "KYD":
      return ["KY"];
    case "KZT":
      return ["KZ"];
    case "LAK":
      return ["LA"];
    case "LBP":
      return ["LB"];
    case "LKR":
      return ["LK"];
    case "LRD":
      return ["LR"];
    case "LSL":
      return ["LS"];
    case "MAD":
      return ["MA", "EH"];
    case "MDL":
      return ["MD"];
    case "MKD":
      return ["MK"];
    case "MMK":
      return ["MM"];
    case "MNT":
      return ["MN"];
    case "MOP":
      return ["MO"];
    case "MUR":
      return ["MU"];
    case "MVR":
      return ["MV"];
    case "MWK":
      return ["MW"];
    case "MXN":
      return ["MX"];
    case "MYR":
      return ["MY"];
    case "NAD":
      return ["NA"];
    case "NGN":
      return ["NG"];
    case "NIO":
      return ["NI"];
    case "NOK":
      return ["BV", "NO", "SJ"];
    case "NPR":
      return ["NP"];
    case "NZD":
      return ["NZ", "CK", "NU", "PN", "TK"];
    case "OMR":
      return ["OM"];
    case "PEN":
      return ["PE"];
    case "PGK":
      return ["PG"];
    case "PHP":
      return ["PH"];
    case "PKR":
      return ["PK"];
    case "PLN":
      return ["PL"];
    case "QAR":
      return ["QA"];
    case "RON":
      return ["RO"];
    case "CNY":
      return ["CN"];
    case "RUB":
      return ["RU"];
    case "SAR":
      return ["SA"];
    case "SCR":
      return ["SC"];
    case "SEK":
      return ["SE"];
    case "SGD":
      return ["SG"];
    case "SLL":
      return ["SL"];
    case "SOS":
      return ["SO"];
    case "SSP":
      return ["SS"];
    case "SVC":
      return ["SV"];
    case "SZL":
      return ["SZ"];
    case "THB":
      return ["TH"];
    case "TRY":
      return ["TR"];
    case "TTD":
      return ["TT"];
    case "TWD":
      return ["TW"];
    case "TZS":
      return ["TZ"];
    case "USD":
      return [
        "AS",
        "BQ",
        "IO",
        "EC",
        "SV",
        "GU",
        "HT",
        "MH",
        "FM",
        "MP",
        "PW",
        "PA",
        "PR",
        "TL",
        "TC",
        "US",
        "VG",
        "VI",
      ];
  }
}

export {
  currencyList,
  getCurrencyCodeStringFromVariant,
  getCurrencyCodeFromString,
  getCurrencyNameFromCode,
  getCountryListFromCurrency,
};
/* No side effect */
