// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Modal from "./Modal.bs.js";
import * as React from "react";
import * as Loader from "../components/Loader.bs.js";
import * as RenderIf from "./RenderIf.bs.js";

function LoaderModal(props) {
  var showModal = props.showModal;
  return React.createElement(RenderIf.make, {
    condition: showModal,
    children: React.createElement(Modal.make, {
      showModal: showModal,
      setShowModal: props.setShowModal,
      children: React.createElement(
        "div",
        {
          className: "flex flex-col items-center gap-2",
        },
        React.createElement(Loader.make, {}),
        React.createElement(
          "div",
          {
            className: "text-xl font-semibold mb-4",
          },
          props.text,
        ),
      ),
      modalClass: "w-80 !h-56 flex items-center justify-center m-auto",
      childClass: "flex items-center justify-center h-full w-full",
      paddingClass: "",
    }),
  });
}

var make = LoaderModal;

export { make };
/* Modal Not a pure module */
