// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LogicUtils from "../../utils/LogicUtils.bs.js";
import * as QuickStartUtils from "../Home/QuickStart/QuickStartUtils.bs.js";

function variantToEnumMapper(variantValue) {
  switch (variantValue) {
    case "PLUGIN_CONFIGURE":
      return "ConfigureWoocom";
    case "WEBHOOK_SETUP":
      return "SetupWoocomWebhook";
    case "PROCESSOR_SETUP":
      return "FirstProcessorConnected";
    case "PLUGIN_INSTALL":
    case "COMPLETED_WOOCOMMERCE":
      return "DownloadWoocom";
  }
}

function enumToValueMapper(variantValue, typedValue) {
  switch (variantValue) {
    case "PLUGIN_INSTALL":
      return typedValue.downloadWoocom;
    case "PLUGIN_CONFIGURE":
      return typedValue.configureWoocom;
    case "WEBHOOK_SETUP":
      return typedValue.setupWoocomWebhook;
    case "PROCESSOR_SETUP":
      return LogicUtils.isNonEmptyString(
        typedValue.firstProcessorConnected.processorID,
      );
    case "COMPLETED_WOOCOMMERCE":
      return true;
  }
}

function getSidebarOptionsForWooCommerceIntegration(
  enumDetails,
  wooCommercePageState,
) {
  var currentPageStateEnum = variantToEnumMapper(wooCommercePageState);
  var enumValue = QuickStartUtils.getTypedValueFromDict(
    LogicUtils.safeParse(enumDetails),
  );
  return [
    {
      title: "Download and Install Plugin",
      status: QuickStartUtils.getStatusValue(
        {
          TAG: "Boolean",
          _0: enumValue.downloadWoocom,
        },
        "DownloadWoocom",
        currentPageStateEnum,
      ),
      link: "",
    },
    {
      title: "Configure Plugin",
      status: QuickStartUtils.getStatusValue(
        {
          TAG: "Boolean",
          _0: enumValue.configureWoocom,
        },
        "ConfigureWoocom",
        currentPageStateEnum,
      ),
      link: "",
    },
    {
      title: "Setup Webhook and Save Changes",
      status: QuickStartUtils.getStatusValue(
        {
          TAG: "Boolean",
          _0: enumValue.setupWoocomWebhook,
        },
        "SetupWoocomWebhook",
        currentPageStateEnum,
      ),
      link: "",
    },
    {
      title: "Setup a Processor",
      status: QuickStartUtils.getStatusValue(
        {
          TAG: "String",
          _0: enumValue.firstProcessorConnected.processorID,
        },
        "FirstProcessorConnected",
        currentPageStateEnum,
      ),
      link: "",
    },
  ];
}

export {
  variantToEnumMapper,
  enumToValueMapper,
  getSidebarOptionsForWooCommerceIntegration,
};
/* LogicUtils Not a pure module */
