type messageFromParent =
  | AUTH_TOKEN
  | AUTH_ERROR
  | INIT_CONFIG
  | EMBEDDED_MODAL_OPENED
  | EMBEDDED_MODAL_CLOSED
  | Unknown(string)

type messageToParent =
  | TOKEN_EXPIRED
  | EMBEDDED_IFRAME_READY
  | EMBEDDED_COMPONENT_RESIZE
  | EMBEDDED_MODAL_OPEN
  | EMBEDDED_MODAL_CLOSE
  | EMBEDDED_MODAL_VISIBLE
