type scaExemption = {
  totalThreeDSPayments: int,
  exemptionRequested: int,
  exemptionNotRequested: int,
  exemptionAccepted: int,
  exemptionRejected: int,
  acceptedFrictionless: int,
  rejectedFrictionless: int,
  rejectedChallenge: int,
  rejectedPending: int,
  notRequestedFrictionless: int,
  notRequestedChallenge: int,
  notRequestedPending: int,
  frictionlessTotal: int,
  challengeTotal: int,
  pendingTotal: int,
  frictionlessAuthSuccess: int,
  frictionlessAuthFailure: int,
  frictionlessAuthPending: int,
  challengeAuthSuccess: int,
  challengeAuthFailure: int,
  challengeAuthPending: int,
  authSuccess: int,
  authFailure: int,
}
