type scaExemption = {
  totalThreeDSPayments: int,
  exemptionRequested: int,
  exemptionNotRequested: int,
  exemptionAccepted: int,
  exemptionRejected: int,
  threeDSCompleted: int,
  threeDSIncomplete: int,
  authSuccess: int,
  authFailure: int,
  notRequested3dsCompleted: int,
  notRequested3dsIncomplete: int,
  rejected3dsCompleted: int,
  rejected3dsIncomplete: int,
  acceptedAuthSuccess: int,
  acceptedAuthFailure: int,
  challengeAuthSuccess: int,
  challengeAuthFailure: int,
  challengeIncompleteAuthFailure: int,
}
