// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as APIUtils from "../../../APIUtils/APIUtils.bs.js";
import * as AuditLogUI from "../LogUtils/AuditLogUI.bs.js";
import * as LogicUtils from "../../../../utils/LogicUtils.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function PaymentLogs(props) {
  var createdAt = props.createdAt;
  var paymentId = props.paymentId;
  var getURL = APIUtils.useGetURL();
  var apiLogsUrl = getURL(
    "PAYMENT_LOGS",
    "Get",
    Caml_option.some(paymentId),
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  );
  var sdkLogsUrl = getURL(
    "SDK_EVENT_LOGS",
    "Post",
    Caml_option.some(paymentId),
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  );
  var startTime = new Date(createdAt).getTime() - 1000 * 60 * 5;
  var startTime$1 = new Date(startTime).toISOString();
  var endTime = new Date(createdAt).getTime() + 1000 * 60 * 60 * 3;
  var endTime$1 = new Date(endTime).toISOString();
  var sdkPostBody = LogicUtils.getJsonFromArrayOfJson([
    ["paymentId", paymentId],
    [
      "timeRange",
      Object.fromEntries([
        ["startTime", startTime$1],
        ["endTime", endTime$1],
      ]),
    ],
  ]);
  var webhookLogsUrl = getURL(
    "WEBHOOKS_EVENT_LOGS",
    "Get",
    Caml_option.some(paymentId),
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  );
  var connectorLogsUrl = getURL(
    "CONNECTOR_EVENT_LOGS",
    "Get",
    Caml_option.some(paymentId),
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  );
  var urls = [
    {
      url: apiLogsUrl,
      apiMethod: "Get",
    },
    {
      url: sdkLogsUrl,
      apiMethod: "Post",
      body: sdkPostBody,
    },
    {
      url: webhookLogsUrl,
      apiMethod: "Get",
    },
    {
      url: connectorLogsUrl,
      apiMethod: "Get",
    },
  ];
  return React.createElement(AuditLogUI.make, {
    id: paymentId,
    urls: urls,
    logType: "PAYMENT",
  });
}

var make = PaymentLogs;

export { make };
/* react Not a pure module */
