external formReactEventToString: ReactEvent.Form.t => string = "%identity"
external stringToFormReactEvent: string => ReactEvent.Form.t = "%identity"
external anyTypeToReactEvent: 'a => ReactEvent.Form.t = "%identity"
external arrofStringToReactEvent: array<string> => ReactEvent.Form.t = "%identity"
external jsonToNullableJson: JSON.t => Nullable.t<JSON.t> = "%identity"
external jsonToReactDOMStyle: JSON.t => ReactDOM.style = "%identity"
external genericTypeToJson: 'a => JSON.t = "%identity"
external genericTypeToBool: 'a => bool = "%identity"
external formReactEventToBool: ReactEvent.Form.t => bool = "%identity"
external genericObjectOrRecordToJson: {..} => JSON.t = "%identity"
external genericTypeToDictOfJson: 't => Dict.t<JSON.t> = "%identity"
external formReactEventToArrayOfString: ReactEvent.Form.t => array<string> = "%identity"
external jsonToFormReactEvent: JSON.t => ReactEvent.Form.t = "%identity"
external arrayOfGenericTypeToFormReactEvent: array<'a> => ReactEvent.Form.t = "%identity"
external webAPIFocusEventToReactEventFocus: Webapi.Dom.FocusEvent.t => ReactEvent.Focus.t =
  "%identity"
external toWasm: Dict.t<JSON.t> => RoutingTypes.wasmModule = "%identity"
external jsonToAnyType: JSON.t => 't = "%identity"
external nullableOfAnyTypeToJsonType: Nullable.t<'a> => JSON.t = "%identity"
external dictOfAnyTypeToObj: Dict.t<'a> => {..} = "%identity"
