name: CI Check - Block Label

on:
  pull_request:

jobs:
  check-label:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Check for "blocked" label
        shell: bash
        run: |
          if [[ github.event.label.name = 'S-blocked' ]]
          then
            echo "ABC"  
          else
            echo "BCD"
          fi

   
     

  