name: CI Check - Block Label

on:
  pull_request:

jobs:
  check-label:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for "blocked" label
        if: github.event.label.name == 'S-blocked'
        shell: bash
        run: echo "Checking for blocked label"

   
     

  