name: PR Title Spell Check

on:
  merge_group:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: pr-title-spell-check-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  typos:
    name: Spell check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Store PR title in a file
        shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: printf '%s\n' "$TITLE" > pr_title.txt

      - name: Spell check
        uses: crate-ci/typos@v1.46.2
        with:
          files: ./pr_title.txt
