name: Spell Check

on:
  push:
    branches:
      - main
  merge_group:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: spellcheck-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  typos:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Spell check
        uses: crate-ci/typos@v1.46.2
