name: Update closed PR lables

on:
  # This is a dangerous event trigger as it causes the workflow to run in the
  # context of the target repository.
  # Avoid checking out the head of the pull request or building code from the
  # pull request whenever this trigger is used.
  # Since we only label pull requests, do not have a checkout step in this
  # workflow, and restrict permissions on the token, this is an acceptable
  # use of this trigger.
  pull_request_target:
    types:
      - opened
      - closed

  merge_group:
    types:
      - checks_requested

permissions:
  # Reference: https://github.com/cli/cli/issues/6274
  repository-projects: read
  pull-requests: write

env:
  # Allow more retries for network requests in cargo (downloading crates) and
  # rustup (installing toolchains). This should help to reduce flaky CI failures
  # from transient network timeouts or other issues.
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  # Use cargo's sparse index protocol
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
