name: Update PR Label

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-pr-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update PR Label
        run: |
            echo "Pull Request Number: ${{ github.event.pull_request.number }}"
            echo "Pull Request Title: ${{ github.event.pull_request.title }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
