name: Update PR Label

on:
  pull_request:
    types:
      - opened

jobs:
  update-pr-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update PR Label
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Check if the PR is merged
          if [ "${{ github.event.pull_request.merged }}" == "false" ]; then
            # Update the labels
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -d '{"labels": ["wontfix"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels"
          else
            echo "PR not merged. No label update needed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
